clone:
  git:
    image: plugins/git

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - .yarn-cache
      - ./staff-frontend/node_modules
      - ./export-app-frontend/node_modules
      - ./rublevka-frontend/node_modules
      - ./firebase-functions/node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      branch: [master, develop]
      event: [push]

  build-firebase:
    image: node:8.15.0
    commands:
      - yarn config set cache-folder $(pwd)/.yarn-cache
      - yarn add firebase-tools
      - cd firebase-functions
      - yarn --ignore-engines
    when:
      branch: [master]
      event: [push]

  deploy-rublevka-frontend-dev:
    image: docker/compose:1.22.0
    commands:
      - cd rublevka-frontend
      - docker-compose -f docker-compose-dev.yml build --build-arg BUILD_ID=$DRONE_BUILD_NUMBER
      - docker-compose -f docker-compose-dev.yml up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP=rublevka
      - APP_ENV=development
      - HOST=dev.rublevka.ru
    when:
      branch: [develop]
      event: [push]

  deploy-rublevka-frontend-prod:
    image: docker/compose:1.22.0
    commands:
      - cd rublevka-frontend
      - docker-compose build --build-arg BUILD_ID=$DRONE_BUILD_NUMBER
      - docker-compose up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP=rublevka
      - APP_ENV=production
      - HOST=rublevka.ru
    secrets:
      - source: react_app_roistat_id_rublevka_ru
        target: react_app_roistat_id
      - source: react_app_targetix_pixel_id_rublevka_ru
        target: react_app_targetix_pixel_id
      - source: react_app_facebook_pixel_id_rublevka_ru
        target: react_app_facebook_pixel_id
      - source: react_app_google_analytics_id_rublevka_ru
        target: react_app_google_analytics_id
      - source: react_app_yandex_metrika_id_rublevka_ru
        target: react_app_yandex_metrika_id
    when:
      branch: [master]
      event: [push]

  build-staff-frontend-prod:
    image: node:8.15.0
    commands:
      - yarn config set cache-folder $(pwd)/.yarn-cache
      - cd staff-frontend
      - yarn --ignore-engines
      - yarn build
    secrets:
      - source: react_app_env_staff_rublevka_ru
        target: react_app_env
      - source: react_app_yandex_metrika_id_staff_rublevka_ru
        target: react_app_yandex_metrika_id
      - source: react_app_sentry_dsn_staff_rublevka_ru
        target: react_app_sentry_dsn
      - source: react_app_firebase_functions_url
        target: react_app_firebase_functions_url
    when:
      branch: [master]
      event: [push]

  build-export-app-frontend-prod:
    image: node:8.15.0
    commands:
      - yarn config set cache-folder $(pwd)/.yarn-cache
      - cd export-app-frontend
      - yarn --ignore-engines
      - yarn build
    secrets:
      [
        react_app_firebase_api_key,
        react_app_firebase_auth_domain,
        react_app_firebase_project_id,
      ]
    when:
      branch: [master]
      event: [push]

  # deploy-backend-dev:
  #   image: docker/compose:1.22.0
  #   commands:
  #     - cd backend
  #     - docker-compose -f devops/docker-compose-dev.yml build
  #     - docker-compose -f devops/docker-compose-dev.yml up -d
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   when:
  #     branch: [develop]
  #     event: [push]

  deploy-firebase-prod:
    image: node:8.15.0
    commands:
      - yarn firebase deploy --token "$FIREBASE_TOKEN" --except hosting:rublevka-frontend-dev
    secrets: [firebase_token]
    when:
      branch: [master]
      event: [push]

  telegram-notification:
    image: appleboy/drone-telegram
    secrets:
      - source: telegram_access_token
        target: telegram_token
      - source: telegram_chat_id
        target: telegram_to
    format: markdown
    message: >
      {{#success build.status}}
      ✅ Build [#{{build.number}}]({{build.link}}) of `{{repo.name}}` succeeded.


      - {{commit.message}} ([{{truncate commit.sha 5}}]({{commit.link}})@{{commit.branch}} by {{commit.author}})
      {{else}}
      ❌ Build [#{{build.number}}]({{build.link}}) of `{{repo.name}}` failed.


      - {{commit.message}} ([{{truncate commit.sha 5}}]({{commit.link}})@{{commit.branch}} by {{commit.author}})
      {{/success}}
    when:
      status: [success, failure]
      branch: [master, develop]
      event: [push]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - .yarn-cache
      - ./staff-frontend/node_modules
      - ./export-app-frontend/node_modules
      - ./rublevka-frontend/node_modules
      - ./firebase-functions/node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      branch: [master, develop]
      event: [push]

branches: [master, develop]
