clone:
  git:
    image: plugins/git

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./staff-frontend/node_modules
      - ./export-app-firebase/node_modules
      - ./export-app-frontend/node_modules
    volumes:
      - /tmp/cache:/cache

  deploy_staff_dev:
    image: docker/compose:1.22.0
    commands:
      - cd backend
      - docker-compose -f devops/docker-compose-dev.yml build
      - docker-compose -f devops/docker-compose-dev.yml up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [develop]
      event: [push]
  deploy_export_app:
    image: node
    commands:
      - npm install -g firebase-tools

      - cd export-app-firebase
      - npm install

      - cd ../export-app-frontend
      - npm install
      - npm run build

      - cd ../staff-frontend
      - npm install
      - npm run build

      - firebase deploy --token "$FIREBASE_TOKEN"
    secrets:
      [
        react_app_firebase_api_key,
        react_app_firebase_auth_domain,
        react_app_firebase_project_id,
        firebase_token,
        react_app_env,
        react_app_staff_sentry_dsn,
      ]
    when:
      branch: [develop]
      event: [push]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./staff-frontend/node_modules
      - ./export-app-firebase/node_modules
      - ./export-app-frontend/node_modules
    volumes:
      - /tmp/cache:/cache

branches: [master, develop]
