clone:
  git:
    image: plugins/git

pipeline:
  deploy_dev:
    image: docker/compose:1.22.0
    commands:
      - cd staff-frontend/
      - docker-compose -f docker-compose-dev.yml build
      - docker-compose -f docker-compose-dev.yml up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [develop]
      event: [push]

branches: [master, develop]
