FROM node:10.15-alpine

HEALTHCHECK CMD curl --fail http://localhost:80/ || exit 1

RUN apk add --no-cache curl
RUN mkdir /app

WORKDIR /app
COPY . /app

ARG APP
ARG APP_ENV
ARG REACT_APP_SENTRY_DSN
ARG REACT_APP_FACEBOOK_PIXEL_ID
ARG REACT_APP_TARGETIX_PIXEL_ID
ARG REACT_APP_ROISTAT_ID
ARG REACT_APP_GOOGLE_ANALYTICS_ID
ARG REACT_APP_YANDEX_METRIKA_ID
ARG REACT_APP_UIS_ID
ARG BUILD_ID
ARG HOST

ENV APP=$APP
ENV APP_ENV=$APP_ENV
ENV REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN
ENV REACT_APP_FACEBOOK_PIXEL_ID=$REACT_APP_FACEBOOK_PIXEL_ID
ENV REACT_APP_TARGETIX_PIXEL_ID=$REACT_APP_TARGETIX_PIXEL_ID
ENV REACT_APP_ROISTAT_ID=$REACT_APP_ROISTAT_ID
ENV REACT_APP_GOOGLE_ANALYTICS_ID=$REACT_APP_GOOGLE_ANALYTICS_ID
ENV REACT_APP_YANDEX_METRIKA_ID=$REACT_APP_YANDEX_METRIKA_ID
ENV REACT_APP_UIS_ID=$REACT_APP_UIS_ID
ENV BUILD_ID=$BUILD_ID
ENV HOST=$HOST
ENV PORT=80

RUN yarn --ignore-engines
RUN NODE_ENV=production HOST=$HOST APP_ENV=$APP_ENV yarn build

CMD NODE_ENV=production yarn start
