from sqlalchemy import Table, Column, Integer, BigInteger, String, Text, Date, DateTime, Boolean, Float, SmallInteger
from sqlalchemy.dialects.postgresql import ARRAY, JSON, ENUM, DOUBLE_PRECISION
from sqlalchemy.sql.sqltypes import NullType

from .core import db
from .types import CIText


t_client_leads_view = Table(
    'client_leads_view', db.metadata,
    Column('id', Integer),
    Column('call_session_id', BigInteger),
    Column('cbu_id', Integer),
    Column('cbu_department_id', Integer),
    Column('cbu_division_id', Integer),
    Column('cd_email', String(255)),
    Column('cd_first_name', String(255)),
    Column('cd_kind_dictionary_id', Integer),
    Column('cd_last_name', String(255)),
    Column('cd_phone_number', String(255)),
    Column('client_lead_source_id', Integer),
    Column('contact_id', Integer),
    Column('created_at', DateTime(True)),
    Column('deal_id', Integer),
    Column('is_repeated', Boolean),
    Column('kind', ENUM('phone_call', 'online', 'recommendation', name='client_lead_kind')),
    Column('note', Text),
    Column('pcd_call_recording_url', Text),
    Column('pcd_duration', Integer),
    Column('pcd_reason', String(255)),
    Column('pcd_status', ENUM('in_progress', 'successful', 'unsuccessful', 'to_do', name='phone_call_status')),
    Column('property_id', Integer),
    Column('request_kind', ENUM('selling', 'purchase', name='client_lead_request_kind')),
    Column('ru_id', Integer),
    Column('ru_department_id', Integer),
    Column('ru_division_id', Integer),
    Column('sd_reason_id', Integer),
    Column('sd_to_approve', ENUM('in_progress', 'processed', 'rejected', 'new', 'spam', name='client_lead_state')),
    Column('search_query', Text),
    Column('state', ENUM('in_progress', 'processed', 'rejected', 'new', 'spam', name='client_lead_state')),
    Column('ua_client_id', String(255)),
    Column('updated_at', DateTime(True)),
    Column('updated_by_user_id', Integer),
    Column('rd_objects', Text),
    Column('rd_offer_kind', Text),
    Column('rd_category', Text),
    Column('rd_kind', Text),
    Column('rd_price_from', JSON),
    Column('rd_price_to', JSON),
    Column('rd_currency', Text),
    Column('rd_renovate', Text),
    Column('rd_condition', Text),
    Column('rd_furniture', Text),
    Column('rd_country_area_from', JSON),
    Column('rd_country_area_to', JSON),
    Column('rd_country_bedrooms_from', JSON),
    Column('rd_country_bedrooms_to', JSON),
    Column('rd_country_land_area_from', JSON),
    Column('rd_country_land_area_to', JSON),
    Column('rd_country_location_route_id', JSON),
    Column('rd_country_location_locality_id', JSON),
    Column('rd_country_location_settlement_id', JSON),
    Column('rd_country_location_mkad_distance_from', JSON),
    Column('rd_country_location_mkad_distance_to', JSON),
    Column('rd_city_', JSON),
    Column('rd_city_area_from', JSON),
    Column('rd_city_area_to', JSON),
    Column('rd_city_living_area_from', JSON),
    Column('rd_city_living_area_to', JSON),
    Column('rd_city_rooms_from', JSON),
    Column('rd_city_rooms_to', JSON),
    Column('rd_city_sublocality_id', JSON),
    Column('rd_city_street', JSON),
    Column('rd_rent_offer_price', JSON),
    Column('rd_rent_offer_currency', JSON),
    Column('rd_rent_offer_agent_fee', JSON),
    Column('rd_rent_offer_agent_fixed_price_currency', Text),
    Column('rd_rent_offer_agent_fixed_price_price', JSON),
    Column('rd_rent_offer_deposit', JSON),
    Column('rd_rent_offer_period', JSON),
    Column('rd_rent_offer_is_allowed_pets', JSON),
    Column('rd_rent_offer_is_allowed_children', JSON),
    Column('rd_sale_offer_price', JSON),
    Column('rd_sale_offer_currency', Text),
    Column('rd_sale_offer_agent_fee', JSON),
    Column('rd_sale_offer_agent_fixed_price_currency', Text),
    Column('rd_sale_offer_agent_fixed_price_price', JSON),
    Column('rd_sale_offer_kind', Text),
    Column('rd_sale_offer_is_bargain', JSON),
    Column('rd_sale_offer_is_mortgage', JSON),
    Column('rd_sale_offer_is_installment', JSON),
    Column('rd_sale_offer_is_resale', JSON),
    Column('utm_campaign', Text),
    Column('utm_source', Text),
    Column('utm_term', Text),
    Column('utm_content', Text),
    Column('utm_medium', Text)
)

t_country_properties_view = Table(
    'country_properties_view', db.metadata,
    Column('id', Integer),
    Column('ru_id', Integer),
    Column('state',
           ENUM('draft', 'public', 'postponed', 'sold', 'rented', 'private', 'deleted', name='property_state')),
    Column('kind',
           ENUM('flat', 'room', 'house', 'land', 'office', 'warehouse', 'townhouse', 'apartment', 'private',
                'penthouse', 'commercial_space', name='property_kind')),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('created_by_user_id', Integer),
    Column('updated_by_user_id', Integer),
    Column('client_lead_id', Integer),
    Column('category', ENUM('commercial', 'city', 'country', name='property_category')),
    Column('ro_price', BigInteger),
    Column('ro_currency', ENUM('RUB', 'USD', 'EUR', name='currency')),
    Column('ro_agent_fee', Float),
    Column('ro_agent_fixed_price', Integer),
    Column('ro_agent_fixed_price_currency', ENUM('RUB', 'USD', 'EUR', name='currency')),
    Column('ro_deposit', SmallInteger),
    Column('ro_period', ENUM('day', 'month', 'year', name='rent_period')),
    Column('ro_is_allowed_pets', Boolean),
    Column('ro_is_allowed_children', Boolean),
    Column('so_price', BigInteger),
    Column('so_currency', ENUM('RUB', 'USD', 'EUR', name='currency')),
    Column('so_agent_fee', Float),
    Column('so_agent_fixed_price', Integer),
    Column('so_agent_fixed_price_currency', ENUM('RUB', 'USD', 'EUR', name='currency')),
    Column('so_kind', ENUM('direct_sell', 'trade_in', 'changing', 'fl214', 'assignment', name='sale_offer_kind')),
    Column('so_is_bargain', Boolean),
    Column('so_is_mortgage', Boolean),
    Column('so_is_installment', Boolean),
    Column('note', Text),
    Column('ru_department_id', Integer),
    Column('ru_division_id', Integer),
    Column('removal_order_id', Integer),
    Column('sd_reason', Text),
    Column('so_is_resale', Boolean),
    Column('external_id', String(255)),
    Column('l_cadastral_number', String(255)),
    Column('badge_id', Integer),
    Column('so_price_delta', BigInteger),
    Column('ro_price_delta', BigInteger),
    Column('ad_security_house_area', Float),
    Column('ad_guest_house_area', Float),
    Column('ad_staff_house_area', Float),
    Column('ad_spa_area', Float),
    Column('ad_pool_width', SmallInteger),
    Column('ad_pool_height', SmallInteger),
    Column('ad_parking_area', Float),
    Column('ad_garage_area', Float),
    Column('c_power_supply', SmallInteger),
    Column('c_water_supply', ENUM('purification', 'central', 'well', name='water_type')),
    Column('c_gas_supply', ENUM('without_gas', 'gas_holder', 'near_border', 'mains', 'diesel', name='gas_type')),
    Column('c_sewerage_supply', ENUM('central', 'septic', name='sewerage_type')),
    Column('ld_landscaping', Boolean),
    Column('ld_area', Float),
    Column('l_street', String(255)),
    Column('l_house', String(255)),
    Column('s_bedrooms', SmallInteger),
    Column('s_area', Float),
    Column('s_wall_material',
           ENUM('blue_max', 'wood', 'brick', 'block', 'monolith', 'canadian_sip', name='wall_material')),
    Column('s_roof_material',
           ENUM('steel', 'soft_tile', 'copper', 'metal_tile', 'slate', 'tile', 'rooftop', name='roof_material')),
    Column('s_built_year', SmallInteger),
    Column('s_floors', SmallInteger),
    Column('s_loggias', SmallInteger),
    Column('s_balconies', SmallInteger),
    Column('s_elevators', SmallInteger),
    Column('s_ceiling_height', Float),
    Column('s_with_conditioning', Boolean),
    Column('s_with_ventilation', Boolean),
    Column('s_renovate',
           ENUM('design', 'rough_finish', 'full_construction', 'partly_turnkey', 'for_finishing', 'raw',
                name='property_renovate')),
    Column('s_condition', ENUM('great', 'good', 'normal', 'bad', name='property_condition')),
    Column('s_furniture', ENUM('full', 'partial', 'absent', name='property_furniture')),
    Column('l_settlement_id', Integer),
    Column('l_country_id', Integer),
    Column('l_region_id', Integer),
    Column('l_district_id', Integer),
    Column('l_locality_id', Integer),
    Column('ad_bathhouse_area', Float),
    Column('l_route_id', Integer),
    Column('l_latitude', String(255)),
    Column('l_longitude', String(255)),
    Column('s_rooms', SmallInteger),
    Column('s_wcs', SmallInteger),
    Column('equipment_internet', Boolean),
    Column('equipment_phone', Boolean),
    Column('equipment_tv', Boolean),
    Column('equipment_security_signaling', Boolean),
    Column('equipment_cable_tv', Boolean),
    Column('equipment_washmachine', Boolean),
    Column('equipment_intercom', Boolean),
    Column('equipment_fridge', Boolean),
    Column('equipment_dishwasher', Boolean),
    Column('equipment_appliances', Boolean),
    Column('ld_landscape_kind', Text),
    Column('s_layouts_wine_rooms', Integer),
    Column('s_layouts_dressing_rooms', Integer),
    Column('s_layouts_living_rooms', Integer),
    Column('s_layouts_childrens_rooms', Integer),
    Column('s_layouts_movie_theaters', Integer),
    Column('s_layouts_winter_gardens', Integer),
    Column('s_layouts_gamerooms', Integer),
    Column('s_layouts_offices', Integer),
    Column('s_layouts_storages', Integer),
    Column('s_layouts_kitchens', Integer),
    Column('s_layouts_staff_rooms', Integer),
    Column('s_layouts_working_kitchens', Integer),
    Column('s_layouts_spa_zones', Integer),
    Column('s_layouts_dining_rooms', Integer),
    Column('s_layouts_technical_rooms', Integer),
    Column('s_layouts_gyms', Integer),
    Column('s_layouts_utility_rooms', Integer),
    Column('s_layouts_lofts', Integer),
    Column('owner_contact_id', Integer),
    Column('representative_contact_id', Integer),
    Column('images', Text),
    Column('layout_images', Text)
)

t_geography_columns = Table(
    'geography_columns', db.metadata,
    Column('f_table_catalog', String),
    Column('f_table_schema', String),
    Column('f_table_name', String),
    Column('f_geography_column', String),
    Column('coord_dimension', Integer),
    Column('srid', Integer),
    Column('type', Text)
)

t_geometry_columns = Table(
    'geometry_columns', db.metadata,
    Column('f_table_catalog', String(256)),
    Column('f_table_schema', String),
    Column('f_table_name', String),
    Column('f_geometry_column', String),
    Column('coord_dimension', Integer),
    Column('srid', Integer),
    Column('type', String(30))
)

t_popular_properties = Table(
    'popular_properties', db.metadata,
    Column('id', Integer),
    Column('category', ENUM('commercial', 'city', 'country', name='property_category')),
    Column('deals_count', BigInteger),
    Column('client_leads_count', BigInteger)
)

t_raster_columns = Table(
    'raster_columns', db.metadata,
    Column('r_table_catalog', String),
    Column('r_table_schema', String),
    Column('r_table_name', String),
    Column('r_raster_column', String),
    Column('srid', Integer),
    Column('scale_x', Float(53)),
    Column('scale_y', Float(53)),
    Column('blocksize_x', Integer),
    Column('blocksize_y', Integer),
    Column('same_alignment', Boolean),
    Column('regular_blocking', Boolean),
    Column('num_bands', Integer),
    Column('pixel_types', ARRAY(Text())),
    Column('nodata_values', ARRAY(DOUBLE_PRECISION(precision=53))),
    Column('out_db', Boolean),
    # Column('extent', NullType),  # type: geometry
    Column('spatial_index', Boolean)
)

t_raster_overviews = Table(
    'raster_overviews', db.metadata,
    Column('o_table_catalog', String),
    Column('o_table_schema', String),
    Column('o_table_name', String),
    Column('o_raster_column', String),
    Column('r_table_catalog', String),
    Column('r_table_schema', String),
    Column('r_table_name', String),
    Column('r_raster_column', String),
    Column('overview_factor', Integer)
)

t_settlements_view = Table(
    'settlements_view', db.metadata,
    Column('id', Integer),
    Column('name', CIText),
    Column('kind_name', String(255)),
    Column('aliases', ARRAY(CIText)),
    Column('created_at', DateTime(True)),
    Column('updated_at', DateTime(True)),
    Column('state', ENUM('draft', 'public', name='model_state')),
    Column('kind_dictionary_kind',
           ENUM('staff_document_type', 'contact_link_type', 'department', 'position', 'property_document_type',
                'property_contact_link_type', 'auto_brand', 'auto_model', 'contact_occupation',
                'contact_job_role', 'contact_position', 'contact_document_type', 'complex_building_document_type',
                'settlement_type', 'settlement_external_infrastructure', 'settlement_internal_infrastructure',
                'settlement_document_type', 'deal_contact_type', 'property_contract_type', 'property_banner',
                'place_contact_type', 'client_lead_targeted_reject_reason',
                'client_lead_non_targeted_reject_reason', 'spam_reason', name='dictionary_kind')),
    Column('kind_dictionary_id', Integer),
    Column('main_sale_description', Text),
    Column('satellite_sale_description', Text),
    Column('images', JSON),
    Column('created_by_user_id', Integer),
    Column('updated_by_user_id', Integer),
    Column('l_mkad_distance', SmallInteger),
    Column('l_country_id', Integer),
    Column('l_region_id', Integer),
    Column('l_district_id', Integer),
    Column('l_locality_id', Integer),
    Column('d_foundation_year', SmallInteger),
    Column('d_area', Float),
    Column('d_power_supply', SmallInteger),
    Column('d_water_supply', ENUM('purification', 'central', 'well', name='water_type')),
    Column('d_gas_supply', ENUM('without_gas', 'gas_holder', 'near_border', 'mains', 'diesel', name='gas_type')),
    Column('d_sewerage_supply', ENUM('central', 'septic', name='sewerage_type')),
    Column('l_route_id', Integer),
    Column('pd_so_kind',
           ENUM('direct_sell', 'trade_in', 'changing', 'fl214', 'assignment', name='sale_offer_kind')),
    Column('pd_so_is_bargain', Boolean),
    Column('pd_so_is_installment', Boolean),
    Column('pd_so_is_mortgage', Boolean),
    Column('pd_so_agent_fee', Float),
    Column('pd_so_agent_fixed_price', BigInteger),
    Column('pd_so_agent_fixed_price_currency', ENUM('RUB', 'USD', 'EUR', name='currency')),
    Column('ru_id', Integer),
    Column('ru_department_id', Integer),
    Column('ru_division_id', Integer),
    # Column('l_pos', NullType),  # geography
    Column('main_rent_description', Text),
    Column('satellite_rent_description', Text),
    Column('land_state_individual_housing', Boolean),
    Column('land_state_gardening_partnership', Boolean),
    Column('land_state_non_commercial_partnership', Boolean),
    Column('d_external_infrastructure', Text),
    Column('d_internal_infrastructure', Text),
    Column('lat', Float(53)),
    Column('lon', Float(53))
)
