export default {
  updatedAt: '',
  communication: {
    sewerageSupply: '',
    gasSupply: '',
    powerSupply: 0,
    waterSupply: '',
  },
  location: {
    latitude: '',
    districtId: 0,
    localityId: 0,
    settlementName: '',
    settlementId: 0,
    countryName: '',
    routeId: 0,
    districtName: '',
    longitude: '',
    mkadDistance: 0,
    countryId: 0,
    house: '',
    routeName: '',
    localityName: '',
    street: null,
    regionId: 0,
    regionName: '',
  },
  externalId: null,
  rentOffer: null,
  state: '',
  saleOffer: {
    isMortgage: false,
    priceDelta: null,
    agentFixedPrice: null,
    price: '—',
    agentFee: 0,
    isBargain: false,
    isResale: true,
    multiCurrencyPrice: {
      eur: 0,
      usd: 0,
      rub: 0,
    },
    currency: '',
    kind: '',
    isDisabled: false,
    isInstallment: false,
  },
  clientLeadId: null,
  linkedContactIds: [],
  additionalDetails: {
    garageArea: 0,
    parkingArea: null,
    bathhouseArea: null,
    staffHouseArea: null,
    spaArea: null,
    securityHouseArea: null,
    guestHouseArea: null,
  },
  stateDetails: {
    reason: null,
  },
  responsibleUser: {
    departmentId: 0,
    id: 0,
    divisionId: null,
  },
  createdByUserId: 0,
  layoutImages: [],
  specification: {
    loggias: null,
    bedrooms: 0,
    area: 0,
    elevators: null,
    balconies: null,
    roofMaterial: 'tile',
    legacyLayouts: [],
    renovate: null,
    layouts: {},
    wcs: 0,
    rooms: null,
    ceilingHeight: null,
    withVentilation: false,
    wallMaterial: '',
    condition: null,
    floors: 0,
    furniture: null,
    builtYear: 0,
    spaces: [],
    withConditioning: false,
  },
  id: 18286,
  removalOrderId: null,
  updatedByUserId: 0,
  createdAt: '',
  badge: null,
  category: '',
  equipment: [],
  kind: '',
  images: [],
  landDetails: {
    area: 0,
    landscapeKind: [],
    landscaping: false,
  },
};
