# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class ApiErrorResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, type=None, message=None):  # noqa: E501
        """ApiErrorResponse - a model defined in OpenAPI

        :param code: The code of this ApiErrorResponse.  # noqa: E501
        :type code: int
        :param type: The type of this ApiErrorResponse.  # noqa: E501
        :type type: str
        :param message: The message of this ApiErrorResponse.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': int,
            'type': str,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'type': 'type',
            'message': 'message'
        }

        self._code = code
        self._type = type
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ApiErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiErrorResponse of this ApiErrorResponse.  # noqa: E501
        :rtype: ApiErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this ApiErrorResponse.


        :return: The code of this ApiErrorResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ApiErrorResponse.


        :param code: The code of this ApiErrorResponse.
        :type code: int
        """

        self._code = code

    @property
    def type(self):
        """Gets the type of this ApiErrorResponse.


        :return: The type of this ApiErrorResponse.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ApiErrorResponse.


        :param type: The type of this ApiErrorResponse.
        :type type: str
        """

        self._type = type

    @property
    def message(self):
        """Gets the message of this ApiErrorResponse.


        :return: The message of this ApiErrorResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ApiErrorResponse.


        :param message: The message of this ApiErrorResponse.
        :type message: str
        """

        self._message = message
