# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class Communication(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sewerage_supply=None, gas_supply=None, power_supply=None, water_supply=None):  # noqa: E501
        """Communication - a model defined in OpenAPI

        :param sewerage_supply: The sewerage_supply of this Communication.  # noqa: E501
        :type sewerage_supply: str
        :param gas_supply: The gas_supply of this Communication.  # noqa: E501
        :type gas_supply: str
        :param power_supply: The power_supply of this Communication.  # noqa: E501
        :type power_supply: int
        :param water_supply: The water_supply of this Communication.  # noqa: E501
        :type water_supply: str
        """
        self.openapi_types = {
            'sewerage_supply': str,
            'gas_supply': str,
            'power_supply': int,
            'water_supply': str
        }

        self.attribute_map = {
            'sewerage_supply': 'sewerageSupply',
            'gas_supply': 'gasSupply',
            'power_supply': 'powerSupply',
            'water_supply': 'waterSupply'
        }

        self._sewerage_supply = sewerage_supply
        self._gas_supply = gas_supply
        self._power_supply = power_supply
        self._water_supply = water_supply

    @classmethod
    def from_dict(cls, dikt) -> 'Communication':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Communication of this Communication.  # noqa: E501
        :rtype: Communication
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sewerage_supply(self):
        """Gets the sewerage_supply of this Communication.


        :return: The sewerage_supply of this Communication.
        :rtype: str
        """
        return self._sewerage_supply

    @sewerage_supply.setter
    def sewerage_supply(self, sewerage_supply):
        """Sets the sewerage_supply of this Communication.


        :param sewerage_supply: The sewerage_supply of this Communication.
        :type sewerage_supply: str
        """

        self._sewerage_supply = sewerage_supply

    @property
    def gas_supply(self):
        """Gets the gas_supply of this Communication.


        :return: The gas_supply of this Communication.
        :rtype: str
        """
        return self._gas_supply

    @gas_supply.setter
    def gas_supply(self, gas_supply):
        """Sets the gas_supply of this Communication.


        :param gas_supply: The gas_supply of this Communication.
        :type gas_supply: str
        """

        self._gas_supply = gas_supply

    @property
    def power_supply(self):
        """Gets the power_supply of this Communication.


        :return: The power_supply of this Communication.
        :rtype: int
        """
        return self._power_supply

    @power_supply.setter
    def power_supply(self, power_supply):
        """Sets the power_supply of this Communication.


        :param power_supply: The power_supply of this Communication.
        :type power_supply: int
        """

        self._power_supply = power_supply

    @property
    def water_supply(self):
        """Gets the water_supply of this Communication.


        :return: The water_supply of this Communication.
        :rtype: str
        """
        return self._water_supply

    @water_supply.setter
    def water_supply(self, water_supply):
        """Sets the water_supply of this Communication.


        :param water_supply: The water_supply of this Communication.
        :type water_supply: str
        """

        self._water_supply = water_supply
