# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class CountryPropertyResponsibleUser(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, department_id=None, division_id=None):  # noqa: E501
        """CountryPropertyResponsibleUser - a model defined in OpenAPI

        :param id: The id of this CountryPropertyResponsibleUser.  # noqa: E501
        :type id: int
        :param department_id: The department_id of this CountryPropertyResponsibleUser.  # noqa: E501
        :type department_id: int
        :param division_id: The division_id of this CountryPropertyResponsibleUser.  # noqa: E501
        :type division_id: int
        """
        self.openapi_types = {
            'id': int,
            'department_id': int,
            'division_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'department_id': 'departmentId',
            'division_id': 'divisionId'
        }

        self._id = id
        self._department_id = department_id
        self._division_id = division_id

    @classmethod
    def from_dict(cls, dikt) -> 'CountryPropertyResponsibleUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CountryProperty_responsibleUser of this CountryPropertyResponsibleUser.  # noqa: E501
        :rtype: CountryPropertyResponsibleUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this CountryPropertyResponsibleUser.


        :return: The id of this CountryPropertyResponsibleUser.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CountryPropertyResponsibleUser.


        :param id: The id of this CountryPropertyResponsibleUser.
        :type id: int
        """

        self._id = id

    @property
    def department_id(self):
        """Gets the department_id of this CountryPropertyResponsibleUser.


        :return: The department_id of this CountryPropertyResponsibleUser.
        :rtype: int
        """
        return self._department_id

    @department_id.setter
    def department_id(self, department_id):
        """Sets the department_id of this CountryPropertyResponsibleUser.


        :param department_id: The department_id of this CountryPropertyResponsibleUser.
        :type department_id: int
        """

        self._department_id = department_id

    @property
    def division_id(self):
        """Gets the division_id of this CountryPropertyResponsibleUser.


        :return: The division_id of this CountryPropertyResponsibleUser.
        :rtype: int
        """
        return self._division_id

    @division_id.setter
    def division_id(self, division_id):
        """Sets the division_id of this CountryPropertyResponsibleUser.


        :param division_id: The division_id of this CountryPropertyResponsibleUser.
        :type division_id: int
        """

        self._division_id = division_id
