# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class Country(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, property_categories=None, aliases=None, created_at=None, updated_at=None):  # noqa: E501
        """Country - a model defined in OpenAPI

        :param id: The id of this Country.  # noqa: E501
        :type id: int
        :param name: The name of this Country.  # noqa: E501
        :type name: str
        :param property_categories: The property_categories of this Country.  # noqa: E501
        :type property_categories: List[str]
        :param aliases: The aliases of this Country.  # noqa: E501
        :type aliases: List[str]
        :param created_at: The created_at of this Country.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Country.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'property_categories': List[str],
            'aliases': List[str],
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'property_categories': 'propertyCategories',
            'aliases': 'aliases',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._id = id
        self._name = name
        self._property_categories = property_categories
        self._aliases = aliases
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Country':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Country of this Country.  # noqa: E501
        :rtype: Country
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Country.


        :return: The id of this Country.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Country.


        :param id: The id of this Country.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Country.


        :return: The name of this Country.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Country.


        :param name: The name of this Country.
        :type name: str
        """

        self._name = name

    @property
    def property_categories(self):
        """Gets the property_categories of this Country.


        :return: The property_categories of this Country.
        :rtype: List[str]
        """
        return self._property_categories

    @property_categories.setter
    def property_categories(self, property_categories):
        """Sets the property_categories of this Country.


        :param property_categories: The property_categories of this Country.
        :type property_categories: List[str]
        """

        self._property_categories = property_categories

    @property
    def aliases(self):
        """Gets the aliases of this Country.


        :return: The aliases of this Country.
        :rtype: List[str]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this Country.


        :param aliases: The aliases of this Country.
        :type aliases: List[str]
        """

        self._aliases = aliases

    @property
    def created_at(self):
        """Gets the created_at of this Country.

        The date of creation  # noqa: E501

        :return: The created_at of this Country.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Country.

        The date of creation  # noqa: E501

        :param created_at: The created_at of this Country.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this Country.

        The date of updation  # noqa: E501

        :return: The updated_at of this Country.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Country.

        The date of updation  # noqa: E501

        :param updated_at: The updated_at of this Country.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
