# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class DistrictLocation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, country_id=None, country_name=None, region_id=None, region_name=None):  # noqa: E501
        """DistrictLocation - a model defined in OpenAPI

        :param country_id: The country_id of this DistrictLocation.  # noqa: E501
        :type country_id: int
        :param country_name: The country_name of this DistrictLocation.  # noqa: E501
        :type country_name: str
        :param region_id: The region_id of this DistrictLocation.  # noqa: E501
        :type region_id: int
        :param region_name: The region_name of this DistrictLocation.  # noqa: E501
        :type region_name: str
        """
        self.openapi_types = {
            'country_id': int,
            'country_name': str,
            'region_id': int,
            'region_name': str
        }

        self.attribute_map = {
            'country_id': 'countryId',
            'country_name': 'countryName',
            'region_id': 'regionId',
            'region_name': 'regionName'
        }

        self._country_id = country_id
        self._country_name = country_name
        self._region_id = region_id
        self._region_name = region_name

    @classmethod
    def from_dict(cls, dikt) -> 'DistrictLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The District_location of this DistrictLocation.  # noqa: E501
        :rtype: DistrictLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def country_id(self):
        """Gets the country_id of this DistrictLocation.


        :return: The country_id of this DistrictLocation.
        :rtype: int
        """
        return self._country_id

    @country_id.setter
    def country_id(self, country_id):
        """Sets the country_id of this DistrictLocation.


        :param country_id: The country_id of this DistrictLocation.
        :type country_id: int
        """

        self._country_id = country_id

    @property
    def country_name(self):
        """Gets the country_name of this DistrictLocation.


        :return: The country_name of this DistrictLocation.
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this DistrictLocation.


        :param country_name: The country_name of this DistrictLocation.
        :type country_name: str
        """

        self._country_name = country_name

    @property
    def region_id(self):
        """Gets the region_id of this DistrictLocation.


        :return: The region_id of this DistrictLocation.
        :rtype: int
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this DistrictLocation.


        :param region_id: The region_id of this DistrictLocation.
        :type region_id: int
        """

        self._region_id = region_id

    @property
    def region_name(self):
        """Gets the region_name of this DistrictLocation.


        :return: The region_name of this DistrictLocation.
        :rtype: str
        """
        return self._region_name

    @region_name.setter
    def region_name(self, region_name):
        """Sets the region_name of this DistrictLocation.


        :param region_name: The region_name of this DistrictLocation.
        :type region_name: str
        """

        self._region_name = region_name
