# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class GetCountryPropertyStateDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reason=None):  # noqa: E501
        """GetCountryPropertyStateDetails - a model defined in OpenAPI

        :param reason: The reason of this GetCountryPropertyStateDetails.  # noqa: E501
        :type reason: str
        """
        self.openapi_types = {
            'reason': str
        }

        self.attribute_map = {
            'reason': 'reason'
        }

        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'GetCountryPropertyStateDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetCountryProperty_stateDetails of this GetCountryPropertyStateDetails.  # noqa: E501
        :rtype: GetCountryPropertyStateDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reason(self):
        """Gets the reason of this GetCountryPropertyStateDetails.


        :return: The reason of this GetCountryPropertyStateDetails.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this GetCountryPropertyStateDetails.


        :param reason: The reason of this GetCountryPropertyStateDetails.
        :type reason: str
        """

        self._reason = reason
