# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class Image(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, height=None, width=None, is_public=None, comment=None):  # noqa: E501
        """Image - a model defined in OpenAPI

        :param id: The id of this Image.  # noqa: E501
        :type id: str
        :param height: The height of this Image.  # noqa: E501
        :type height: int
        :param width: The width of this Image.  # noqa: E501
        :type width: int
        :param is_public: The is_public of this Image.  # noqa: E501
        :type is_public: bool
        :param comment: The comment of this Image.  # noqa: E501
        :type comment: str
        """
        self.openapi_types = {
            'id': str,
            'height': int,
            'width': int,
            'is_public': bool,
            'comment': str
        }

        self.attribute_map = {
            'id': 'id',
            'height': 'height',
            'width': 'width',
            'is_public': 'isPublic',
            'comment': 'comment'
        }

        self._id = id
        self._height = height
        self._width = width
        self._is_public = is_public
        self._comment = comment

    @classmethod
    def from_dict(cls, dikt) -> 'Image':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Image of this Image.  # noqa: E501
        :rtype: Image
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Image.


        :return: The id of this Image.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Image.


        :param id: The id of this Image.
        :type id: str
        """

        self._id = id

    @property
    def height(self):
        """Gets the height of this Image.


        :return: The height of this Image.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this Image.


        :param height: The height of this Image.
        :type height: int
        """

        self._height = height

    @property
    def width(self):
        """Gets the width of this Image.


        :return: The width of this Image.
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this Image.


        :param width: The width of this Image.
        :type width: int
        """

        self._width = width

    @property
    def is_public(self):
        """Gets the is_public of this Image.


        :return: The is_public of this Image.
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this Image.


        :param is_public: The is_public of this Image.
        :type is_public: bool
        """

        self._is_public = is_public

    @property
    def comment(self):
        """Gets the comment of this Image.


        :return: The comment of this Image.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this Image.


        :param comment: The comment of this Image.
        :type comment: str
        """

        self._comment = comment
