# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .pagination import Pagination
from .country_property import CountryProperty
from .. import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None, pagination=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param items: The items of this InlineResponse200.  # noqa: E501
        :type items: List[CountryProperty]
        :param pagination: The pagination of this InlineResponse200.  # noqa: E501
        :type pagination: InlineResponse200Pagination
        """
        self.openapi_types = {
            'items': List[CountryProperty],
            'pagination': Pagination
        }

        self.attribute_map = {
            'items': 'items',
            'pagination': 'pagination'
        }

        self._items = items
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this InlineResponse200.


        :return: The items of this InlineResponse200.
        :rtype: List[CountryProperty]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this InlineResponse200.


        :param items: The items of this InlineResponse200.
        :type items: List[CountryProperty]
        """

        self._items = items

    @property
    def pagination(self):
        """Gets the pagination of this InlineResponse200.


        :return: The pagination of this InlineResponse200.
        :rtype: InlineResponse200Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this InlineResponse200.


        :param pagination: The pagination of this InlineResponse200.
        :type pagination: InlineResponse200Pagination
        """

        self._pagination = pagination
