# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created_by_user_id=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param created_by_user_id: The created_by_user_id of this InlineObject.  # noqa: E501
        :type created_by_user_id: int
        """
        self.openapi_types = {
            'created_by_user_id': int
        }

        self.attribute_map = {
            'created_by_user_id': 'createdByUserId'
        }

        self._created_by_user_id = created_by_user_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: InlineObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_by_user_id(self):
        """Gets the created_by_user_id of this InlineObject.


        :return: The created_by_user_id of this InlineObject.
        :rtype: int
        """
        return self._created_by_user_id

    @created_by_user_id.setter
    def created_by_user_id(self, created_by_user_id):
        """Sets the created_by_user_id of this InlineObject.


        :param created_by_user_id: The created_by_user_id of this InlineObject.
        :type created_by_user_id: int
        """

        self._created_by_user_id = created_by_user_id
