# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class Layout(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, number=None, kind=None, items=None):  # noqa: E501
        """Layout - a model defined in OpenAPI

        :param number: The number of this Layout.  # noqa: E501
        :type number: int
        :param kind: The kind of this Layout.  # noqa: E501
        :type kind: str
        :param items: The items of this Layout.  # noqa: E501
        :type items: List[str]
        """
        self.openapi_types = {
            'number': int,
            'kind': str,
            'items': List[str]
        }

        self.attribute_map = {
            'number': 'number',
            'kind': 'kind',
            'items': 'items'
        }

        self._number = number
        self._kind = kind
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'Layout':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Layout of this Layout.  # noqa: E501
        :rtype: Layout
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number(self):
        """Gets the number of this Layout.


        :return: The number of this Layout.
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this Layout.


        :param number: The number of this Layout.
        :type number: int
        """

        self._number = number

    @property
    def kind(self):
        """Gets the kind of this Layout.


        :return: The kind of this Layout.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this Layout.


        :param kind: The kind of this Layout.
        :type kind: str
        """

        self._kind = kind

    @property
    def items(self):
        """Gets the items of this Layout.


        :return: The items of this Layout.
        :rtype: List[str]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this Layout.


        :param items: The items of this Layout.
        :type items: List[str]
        """

        self._items = items
