# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class LocalityLocation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, country_id=None, country_name=None, region_id=None, region_name=None, district_id=None,
                 district_name=None, route_id=None, route_name=None):  # noqa: E501
        """LocalityLocation - a model defined in OpenAPI

        :param country_id: The country_id of this LocalityLocation.  # noqa: E501
        :type country_id: int
        :param country_name: The country_name of this LocalityLocation.  # noqa: E501
        :type country_name: str
        :param region_id: The region_id of this LocalityLocation.  # noqa: E501
        :type region_id: int
        :param region_name: The region_name of this LocalityLocation.  # noqa: E501
        :type region_name: str
        :param district_id: The district_id of this LocalityLocation.  # noqa: E501
        :type district_id: int
        :param district_name: The district_name of this LocalityLocation.  # noqa: E501
        :type district_name: str
        :param route_id: The route_id of this LocalityLocation.  # noqa: E501
        :type route_id: int
        :param route_name: The route_name of this LocalityLocation.  # noqa: E501
        :type route_name: str
        """
        self.openapi_types = {
            'country_id': int,
            'country_name': str,
            'region_id': int,
            'region_name': str,
            'district_id': int,
            'district_name': str,
            'route_id': int,
            'route_name': str
        }

        self.attribute_map = {
            'country_id': 'countryId',
            'country_name': 'countryName',
            'region_id': 'regionId',
            'region_name': 'regionName',
            'district_id': 'districtId',
            'district_name': 'districtName',
            'route_id': 'routeId',
            'route_name': 'routeName'
        }

        self._country_id = country_id
        self._country_name = country_name
        self._region_id = region_id
        self._region_name = region_name
        self._district_id = district_id
        self._district_name = district_name
        self._route_id = route_id
        self._route_name = route_name

    @classmethod
    def from_dict(cls, dikt) -> 'LocalityLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Locality_location of this LocalityLocation.  # noqa: E501
        :rtype: LocalityLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def country_id(self):
        """Gets the country_id of this LocalityLocation.


        :return: The country_id of this LocalityLocation.
        :rtype: int
        """
        return self._country_id

    @country_id.setter
    def country_id(self, country_id):
        """Sets the country_id of this LocalityLocation.


        :param country_id: The country_id of this LocalityLocation.
        :type country_id: int
        """

        self._country_id = country_id

    @property
    def country_name(self):
        """Gets the country_name of this LocalityLocation.


        :return: The country_name of this LocalityLocation.
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this LocalityLocation.


        :param country_name: The country_name of this LocalityLocation.
        :type country_name: str
        """

        self._country_name = country_name

    @property
    def region_id(self):
        """Gets the region_id of this LocalityLocation.


        :return: The region_id of this LocalityLocation.
        :rtype: int
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this LocalityLocation.


        :param region_id: The region_id of this LocalityLocation.
        :type region_id: int
        """

        self._region_id = region_id

    @property
    def region_name(self):
        """Gets the region_name of this LocalityLocation.


        :return: The region_name of this LocalityLocation.
        :rtype: str
        """
        return self._region_name

    @region_name.setter
    def region_name(self, region_name):
        """Sets the region_name of this LocalityLocation.


        :param region_name: The region_name of this LocalityLocation.
        :type region_name: str
        """

        self._region_name = region_name

    @property
    def district_id(self):
        """Gets the district_id of this LocalityLocation.


        :return: The district_id of this LocalityLocation.
        :rtype: int
        """
        return self._district_id

    @district_id.setter
    def district_id(self, district_id):
        """Sets the district_id of this LocalityLocation.


        :param district_id: The district_id of this LocalityLocation.
        :type district_id: int
        """

        self._district_id = district_id

    @property
    def district_name(self):
        """Gets the district_name of this LocalityLocation.


        :return: The district_name of this LocalityLocation.
        :rtype: str
        """
        return self._district_name

    @district_name.setter
    def district_name(self, district_name):
        """Sets the district_name of this LocalityLocation.


        :param district_name: The district_name of this LocalityLocation.
        :type district_name: str
        """

        self._district_name = district_name

    @property
    def route_id(self):
        """Gets the route_id of this LocalityLocation.


        :return: The route_id of this LocalityLocation.
        :rtype: int
        """
        return self._route_id

    @route_id.setter
    def route_id(self, route_id):
        """Sets the route_id of this LocalityLocation.


        :param route_id: The route_id of this LocalityLocation.
        :type route_id: int
        """

        self._route_id = route_id

    @property
    def route_name(self):
        """Gets the route_name of this LocalityLocation.


        :return: The route_name of this LocalityLocation.
        :rtype: str
        """
        return self._route_name

    @route_name.setter
    def route_name(self, route_name):
        """Sets the route_name of this LocalityLocation.


        :param route_name: The route_name of this LocalityLocation.
        :type route_name: str
        """

        self._route_name = route_name
