# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class Location(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, latitude=None, longitude=None, country_id=None, country_name=None, district_id=None,
                 district_name=None, locality_id=None, locality_name=None, settlement_id=None, settlement_name=None,
                 route_id=None, route_name=None, region_id=None, region_name=None, street=None, house=None,
                 mkad_distance=None):  # noqa: E501
        """Location - a model defined in OpenAPI

        :param latitude: The latitude of this Location.  # noqa: E501
        :type latitude: str
        :param longitude: The longitude of this Location.  # noqa: E501
        :type longitude: str
        :param country_id: The country_id of this Location.  # noqa: E501
        :type country_id: int
        :param country_name: The country_name of this Location.  # noqa: E501
        :type country_name: str
        :param district_id: The district_id of this Location.  # noqa: E501
        :type district_id: int
        :param district_name: The district_name of this Location.  # noqa: E501
        :type district_name: str
        :param locality_id: The locality_id of this Location.  # noqa: E501
        :type locality_id: int
        :param locality_name: The locality_name of this Location.  # noqa: E501
        :type locality_name: str
        :param settlement_id: The settlement_id of this Location.  # noqa: E501
        :type settlement_id: int
        :param settlement_name: The settlement_name of this Location.  # noqa: E501
        :type settlement_name: str
        :param route_id: The route_id of this Location.  # noqa: E501
        :type route_id: int
        :param route_name: The route_name of this Location.  # noqa: E501
        :type route_name: str
        :param region_id: The region_id of this Location.  # noqa: E501
        :type region_id: int
        :param region_name: The region_name of this Location.  # noqa: E501
        :type region_name: str
        :param street: The street of this Location.  # noqa: E501
        :type street: str
        :param house: The house of this Location.  # noqa: E501
        :type house: str
        :param mkad_distance: The mkad_distance of this Location.  # noqa: E501
        :type mkad_distance: int
        """
        self.openapi_types = {
            'latitude': str,
            'longitude': str,
            'country_id': int,
            'country_name': str,
            'district_id': int,
            'district_name': str,
            'locality_id': int,
            'locality_name': str,
            'settlement_id': int,
            'settlement_name': str,
            'route_id': int,
            'route_name': str,
            'region_id': int,
            'region_name': str,
            'street': str,
            'house': str,
            'mkad_distance': int
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude',
            'country_id': 'countryId',
            'country_name': 'countryName',
            'district_id': 'districtId',
            'district_name': 'districtName',
            'locality_id': 'localityId',
            'locality_name': 'localityName',
            'settlement_id': 'settlementId',
            'settlement_name': 'settlementName',
            'route_id': 'routeId',
            'route_name': 'routeName',
            'region_id': 'regionId',
            'region_name': 'regionName',
            'street': 'street',
            'house': 'house',
            'mkad_distance': 'mkadDistance'
        }

        self._latitude = latitude
        self._longitude = longitude
        self._country_id = country_id
        self._country_name = country_name
        self._district_id = district_id
        self._district_name = district_name
        self._locality_id = locality_id
        self._locality_name = locality_name
        self._settlement_id = settlement_id
        self._settlement_name = settlement_name
        self._route_id = route_id
        self._route_name = route_name
        self._region_id = region_id
        self._region_name = region_name
        self._street = street
        self._house = house
        self._mkad_distance = mkad_distance

    @classmethod
    def from_dict(cls, dikt) -> 'Location':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Location of this Location.  # noqa: E501
        :rtype: Location
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self):
        """Gets the latitude of this Location.

        Долгота  # noqa: E501

        :return: The latitude of this Location.
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this Location.

        Долгота  # noqa: E501

        :param latitude: The latitude of this Location.
        :type latitude: str
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this Location.

        Широта  # noqa: E501

        :return: The longitude of this Location.
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this Location.

        Широта  # noqa: E501

        :param longitude: The longitude of this Location.
        :type longitude: str
        """

        self._longitude = longitude

    @property
    def country_id(self):
        """Gets the country_id of this Location.


        :return: The country_id of this Location.
        :rtype: int
        """
        return self._country_id

    @country_id.setter
    def country_id(self, country_id):
        """Sets the country_id of this Location.


        :param country_id: The country_id of this Location.
        :type country_id: int
        """

        self._country_id = country_id

    @property
    def country_name(self):
        """Gets the country_name of this Location.


        :return: The country_name of this Location.
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this Location.


        :param country_name: The country_name of this Location.
        :type country_name: str
        """

        self._country_name = country_name

    @property
    def district_id(self):
        """Gets the district_id of this Location.


        :return: The district_id of this Location.
        :rtype: int
        """
        return self._district_id

    @district_id.setter
    def district_id(self, district_id):
        """Sets the district_id of this Location.


        :param district_id: The district_id of this Location.
        :type district_id: int
        """

        self._district_id = district_id

    @property
    def district_name(self):
        """Gets the district_name of this Location.


        :return: The district_name of this Location.
        :rtype: str
        """
        return self._district_name

    @district_name.setter
    def district_name(self, district_name):
        """Sets the district_name of this Location.


        :param district_name: The district_name of this Location.
        :type district_name: str
        """

        self._district_name = district_name

    @property
    def locality_id(self):
        """Gets the locality_id of this Location.


        :return: The locality_id of this Location.
        :rtype: int
        """
        return self._locality_id

    @locality_id.setter
    def locality_id(self, locality_id):
        """Sets the locality_id of this Location.


        :param locality_id: The locality_id of this Location.
        :type locality_id: int
        """

        self._locality_id = locality_id

    @property
    def locality_name(self):
        """Gets the locality_name of this Location.


        :return: The locality_name of this Location.
        :rtype: str
        """
        return self._locality_name

    @locality_name.setter
    def locality_name(self, locality_name):
        """Sets the locality_name of this Location.


        :param locality_name: The locality_name of this Location.
        :type locality_name: str
        """

        self._locality_name = locality_name

    @property
    def settlement_id(self):
        """Gets the settlement_id of this Location.


        :return: The settlement_id of this Location.
        :rtype: int
        """
        return self._settlement_id

    @settlement_id.setter
    def settlement_id(self, settlement_id):
        """Sets the settlement_id of this Location.


        :param settlement_id: The settlement_id of this Location.
        :type settlement_id: int
        """

        self._settlement_id = settlement_id

    @property
    def settlement_name(self):
        """Gets the settlement_name of this Location.


        :return: The settlement_name of this Location.
        :rtype: str
        """
        return self._settlement_name

    @settlement_name.setter
    def settlement_name(self, settlement_name):
        """Sets the settlement_name of this Location.


        :param settlement_name: The settlement_name of this Location.
        :type settlement_name: str
        """

        self._settlement_name = settlement_name

    @property
    def route_id(self):
        """Gets the route_id of this Location.


        :return: The route_id of this Location.
        :rtype: int
        """
        return self._route_id

    @route_id.setter
    def route_id(self, route_id):
        """Sets the route_id of this Location.


        :param route_id: The route_id of this Location.
        :type route_id: int
        """

        self._route_id = route_id

    @property
    def route_name(self):
        """Gets the route_name of this Location.


        :return: The route_name of this Location.
        :rtype: str
        """
        return self._route_name

    @route_name.setter
    def route_name(self, route_name):
        """Sets the route_name of this Location.


        :param route_name: The route_name of this Location.
        :type route_name: str
        """

        self._route_name = route_name

    @property
    def region_id(self):
        """Gets the region_id of this Location.


        :return: The region_id of this Location.
        :rtype: int
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this Location.


        :param region_id: The region_id of this Location.
        :type region_id: int
        """

        self._region_id = region_id

    @property
    def region_name(self):
        """Gets the region_name of this Location.


        :return: The region_name of this Location.
        :rtype: str
        """
        return self._region_name

    @region_name.setter
    def region_name(self, region_name):
        """Sets the region_name of this Location.


        :param region_name: The region_name of this Location.
        :type region_name: str
        """

        self._region_name = region_name

    @property
    def street(self):
        """Gets the street of this Location.


        :return: The street of this Location.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this Location.


        :param street: The street of this Location.
        :type street: str
        """

        self._street = street

    @property
    def house(self):
        """Gets the house of this Location.


        :return: The house of this Location.
        :rtype: str
        """
        return self._house

    @house.setter
    def house(self, house):
        """Sets the house of this Location.


        :param house: The house of this Location.
        :type house: str
        """

        self._house = house

    @property
    def mkad_distance(self):
        """Gets the mkad_distance of this Location.


        :return: The mkad_distance of this Location.
        :rtype: int
        """
        return self._mkad_distance

    @mkad_distance.setter
    def mkad_distance(self, mkad_distance):
        """Sets the mkad_distance of this Location.


        :param mkad_distance: The mkad_distance of this Location.
        :type mkad_distance: int
        """

        self._mkad_distance = mkad_distance
