# coding: utf-8

from datetime import date, datetime  # noqa: F401

from typing import Optional, List, Dict  # noqa: F401

from ..models.base_model_ import Model
from .. import util


class MultiCurrencyPrice(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, eur=None, usd=None, rub=None):  # noqa: E501
        """MultiCurrencyPrice - a model defined in OpenAPI

        :param eur: The eur of this MultiCurrencyPrice.  # noqa: E501
        :type eur: Optional[float]
        :param usd: The usd of this MultiCurrencyPrice.  # noqa: E501
        :type usd: Optional[float]
        :param rub: The rub of this MultiCurrencyPrice.  # noqa: E501
        :type rub: Optional[float]
        """
        self.openapi_types = {
            'eur': float,
            'usd': float,
            'rub': float
        }

        self.attribute_map = {
            'eur': 'eur',
            'usd': 'usd',
            'rub': 'rub'
        }

        self._eur = eur
        self._usd = usd
        self._rub = rub

    @classmethod
    def from_dict(cls, dikt) -> 'MultiCurrencyPrice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MultiCurrencyPrice of this MultiCurrencyPrice.  # noqa: E501
        :rtype: MultiCurrencyPrice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def eur(self):
        """Gets the eur of this MultiCurrencyPrice.


        :return: The eur of this MultiCurrencyPrice.
        :rtype: float
        """
        return self._eur

    @eur.setter
    def eur(self, eur):
        """Sets the eur of this MultiCurrencyPrice.


        :param eur: The eur of this MultiCurrencyPrice.
        :type eur: float
        """

        self._eur = eur

    @property
    def usd(self):
        """Gets the usd of this MultiCurrencyPrice.


        :return: The usd of this MultiCurrencyPrice.
        :rtype: float
        """
        return self._usd

    @usd.setter
    def usd(self, usd):
        """Sets the usd of this MultiCurrencyPrice.


        :param usd: The usd of this MultiCurrencyPrice.
        :type usd: float
        """

        self._usd = usd

    @property
    def rub(self):
        """Gets the rub of this MultiCurrencyPrice.


        :return: The rub of this MultiCurrencyPrice.
        :rtype: float
        """
        return self._rub

    @rub.setter
    def rub(self, rub):
        """Sets the rub of this MultiCurrencyPrice.


        :param rub: The rub of this MultiCurrencyPrice.
        :type rub: float
        """

        self._rub = rub
