# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class OfferMultiCurrencyPrice(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, eur=None, usd=None, rub=None):  # noqa: E501
        """OfferMultiCurrencyPrice - a model defined in OpenAPI

        :param eur: The eur of this OfferMultiCurrencyPrice.  # noqa: E501
        :type eur: float
        :param usd: The usd of this OfferMultiCurrencyPrice.  # noqa: E501
        :type usd: float
        :param rub: The rub of this OfferMultiCurrencyPrice.  # noqa: E501
        :type rub: float
        """
        self.openapi_types = {
            'eur': float,
            'usd': float,
            'rub': float
        }

        self.attribute_map = {
            'eur': 'eur',
            'usd': 'usd',
            'rub': 'rub'
        }

        self._eur = eur
        self._usd = usd
        self._rub = rub

    @classmethod
    def from_dict(cls, dikt) -> 'OfferMultiCurrencyPrice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Offer_multiCurrencyPrice of this OfferMultiCurrencyPrice.  # noqa: E501
        :rtype: OfferMultiCurrencyPrice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def eur(self):
        """Gets the eur of this OfferMultiCurrencyPrice.


        :return: The eur of this OfferMultiCurrencyPrice.
        :rtype: float
        """
        return self._eur

    @eur.setter
    def eur(self, eur):
        """Sets the eur of this OfferMultiCurrencyPrice.


        :param eur: The eur of this OfferMultiCurrencyPrice.
        :type eur: float
        """

        self._eur = eur

    @property
    def usd(self):
        """Gets the usd of this OfferMultiCurrencyPrice.


        :return: The usd of this OfferMultiCurrencyPrice.
        :rtype: float
        """
        return self._usd

    @usd.setter
    def usd(self, usd):
        """Sets the usd of this OfferMultiCurrencyPrice.


        :param usd: The usd of this OfferMultiCurrencyPrice.
        :type usd: float
        """

        self._usd = usd

    @property
    def rub(self):
        """Gets the rub of this OfferMultiCurrencyPrice.


        :return: The rub of this OfferMultiCurrencyPrice.
        :rtype: float
        """
        return self._rub

    @rub.setter
    def rub(self, rub):
        """Sets the rub of this OfferMultiCurrencyPrice.


        :param rub: The rub of this OfferMultiCurrencyPrice.
        :type rub: float
        """

        self._rub = rub
