# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict, Union  # noqa: F401

from .base_model_ import Model
from .pagination import Pagination
from .country_property import CountryProperty
from .country import Country
from .region import Region
from .district import District
from .locality import Locality
from .sub_locality import SubLocality
from .route import Route
from .. import util

OneOfCountryPropertyCountryRegionDistrictLocalitySubLocalityRoute = Union[
    CountryProperty, Country, Region, District, Locality, SubLocality, Route]


class PaginationWrapper(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None, pagination=None):  # noqa: E501
        """PaginationWrapper - a model defined in OpenAPI

        :param items: The items of this PaginationWrapper.  # noqa: E501
        :type items: List[OneOfCountryPropertyCountryRegionDistrictLocalitySubLocalityRoute]
        :param pagination: The pagination of this PaginationWrapper.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {
            'items': List[OneOfCountryPropertyCountryRegionDistrictLocalitySubLocalityRoute],
            'pagination': Pagination
        }

        self.attribute_map = {
            'items': 'items',
            'pagination': 'pagination'
        }

        self._items = items
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'PaginationWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaginationWrapper of this PaginationWrapper.  # noqa: E501
        :rtype: PaginationWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this PaginationWrapper.


        :return: The items of this PaginationWrapper.
        :rtype: List[OneOfCountryPropertyCountryRegionDistrictLocalitySubLocalityRoute]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this PaginationWrapper.


        :param items: The items of this PaginationWrapper.
        :type items: List[OneOfCountryPropertyCountryRegionDistrictLocalitySubLocalityRoute]
        """

        self._items = items

    @property
    def pagination(self):
        """Gets the pagination of this PaginationWrapper.


        :return: The pagination of this PaginationWrapper.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this PaginationWrapper.


        :param pagination: The pagination of this PaginationWrapper.
        :type pagination: Pagination
        """

        self._pagination = pagination
