# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class Pagination(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, limit=None, offset=None):  # noqa: E501
        """Pagination - a model defined in OpenAPI

        :param total: The total of this Pagination.  # noqa: E501
        :type total: int
        :param limit: The limit of this Pagination.  # noqa: E501
        :type limit: int
        :param offset: The offset of this Pagination.  # noqa: E501
        :type offset: int
        """
        self.openapi_types = {
            'total': int,
            'limit': int,
            'offset': int
        }

        self.attribute_map = {
            'total': 'total',
            'limit': 'limit',
            'offset': 'offset'
        }

        self._total = total
        self._limit = limit
        self._offset = offset

    @classmethod
    def from_dict(cls, dikt) -> 'Pagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pagination of this Pagination.  # noqa: E501
        :rtype: Pagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self):
        """Gets the total of this Pagination.


        :return: The total of this Pagination.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this Pagination.


        :param total: The total of this Pagination.
        :type total: int
        """

        self._total = total

    @property
    def limit(self):
        """Gets the limit of this Pagination.


        :return: The limit of this Pagination.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this Pagination.


        :param limit: The limit of this Pagination.
        :type limit: int
        """

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this Pagination.


        :return: The offset of this Pagination.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this Pagination.


        :param offset: The offset of this Pagination.
        :type offset: int
        """

        self._offset = offset
