# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .communication import Communication
from .get_country_property_additional_details import GetCountryPropertyAdditionalDetails
from .get_country_property_land_details import GetCountryPropertyLandDetails
from .get_country_property_state_details import GetCountryPropertyStateDetails
from .post_put_country_property_location import PostPutCountryPropertyLocation
from .rent_offer import RentOffer
from .sale_offer import SaleOffer
from .specification import Specification
from .staff_user import StaffUser
from .image import Image
from .. import util


class PostPutCountryProperty(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, created_by_user_id=None, created_at=None, updated_at=None, location=None, communication=None,
                 specification=None, external_id=None, rent_offer=None, sale_offer=None, state=None,
                 client_lead_id=None, linked_contact_ids=None, additional_details=None, state_details=None,
                 responsible_user=None, removal_order_id=None, updated_by_user_id=None, badge=None, category=None,
                 equipment=None, kind=None, images=None, layout_images=None, land_details=None):  # noqa: E501
        """PostPutCountryProperty - a model defined in OpenAPI

        :param created_by_user_id: The created_by_user_id of this PostPutCountryProperty.  # noqa: E501
        :type created_by_user_id: int
        :param created_at: The created_at of this PostPutCountryProperty.  # noqa: E501
        :type created_at: str
        :param updated_at: The updated_at of this PostPutCountryProperty.  # noqa: E501
        :type updated_at: str
        :param location: The location of this PostPutCountryProperty.  # noqa: E501
        :type location: PostPutCountryPropertyLocation
        :param communication: The communication of this PostPutCountryProperty.  # noqa: E501
        :type communication: Communication
        :param specification: The specification of this PostPutCountryProperty.  # noqa: E501
        :type specification: Specification
        :param external_id: The external_id of this PostPutCountryProperty.  # noqa: E501
        :type external_id: str
        :param rent_offer: The rent_offer of this PostPutCountryProperty.  # noqa: E501
        :type rent_offer: RentOffer
        :param sale_offer: The sale_offer of this PostPutCountryProperty.  # noqa: E501
        :type sale_offer: SaleOffer
        :param state: The state of this PostPutCountryProperty.  # noqa: E501
        :type state: str
        :param client_lead_id: The client_lead_id of this PostPutCountryProperty.  # noqa: E501
        :type client_lead_id: int
        :param linked_contact_ids: The linked_contact_ids of this PostPutCountryProperty.  # noqa: E501
        :type linked_contact_ids: List[int]
        :param additional_details: The additional_details of this PostPutCountryProperty.  # noqa: E501
        :type additional_details: GetCountryPropertyAdditionalDetails
        :param state_details: The state_details of this PostPutCountryProperty.  # noqa: E501
        :type state_details: GetCountryPropertyStateDetails
        :param responsible_user: The responsible_user of this PostPutCountryProperty.  # noqa: E501
        :type responsible_user: StaffUser
        :param removal_order_id: The removal_order_id of this PostPutCountryProperty.  # noqa: E501
        :type removal_order_id: int
        :param updated_by_user_id: The updated_by_user_id of this PostPutCountryProperty.  # noqa: E501
        :type updated_by_user_id: int
        :param badge: The badge of this PostPutCountryProperty.  # noqa: E501
        :type badge: int
        :param category: The category of this PostPutCountryProperty.  # noqa: E501
        :type category: str
        :param equipment: The equipment of this PostPutCountryProperty.  # noqa: E501
        :type equipment: List[str]
        :param kind: The kind of this PostPutCountryProperty.  # noqa: E501
        :type kind: str
        :param images: The images of this PostPutCountryProperty.  # noqa: E501
        :type images: List[Image]
        :param layout_images: The layout_images of this PostPutCountryProperty.  # noqa: E501
        :type layout_images: List[Image]
        :param land_details: The land_details of this PostPutCountryProperty.  # noqa: E501
        :type land_details: GetCountryPropertyLandDetails
        """
        self.openapi_types = {
            'created_by_user_id': int,
            'created_at': str,
            'updated_at': str,
            'location': PostPutCountryPropertyLocation,
            'communication': Communication,
            'specification': Specification,
            'external_id': str,
            'rent_offer': RentOffer,
            'sale_offer': SaleOffer,
            'state': str,
            'client_lead_id': int,
            'linked_contact_ids': List[int],
            'additional_details': GetCountryPropertyAdditionalDetails,
            'state_details': GetCountryPropertyStateDetails,
            'responsible_user': StaffUser,
            'removal_order_id': int,
            'updated_by_user_id': int,
            'badge': int,
            'category': str,
            'equipment': List[str],
            'kind': str,
            'images': List[Image],
            'layout_images': List[Image],
            'land_details': GetCountryPropertyLandDetails
        }

        self.attribute_map = {
            'created_by_user_id': 'createdByUserId',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt',
            'location': 'location',
            'communication': 'communication',
            'specification': 'specification',
            'external_id': 'externalId',
            'rent_offer': 'rentOffer',
            'sale_offer': 'saleOffer',
            'state': 'state',
            'client_lead_id': 'clientLeadId',
            'linked_contact_ids': 'linkedContactIds',
            'additional_details': 'additionalDetails',
            'state_details': 'stateDetails',
            'responsible_user': 'responsibleUser',
            'removal_order_id': 'removalOrderId',
            'updated_by_user_id': 'updatedByUserId',
            'badge': 'badge',
            'category': 'category',
            'equipment': 'equipment',
            'kind': 'kind',
            'images': 'images',
            'layout_images': 'layoutImages',
            'land_details': 'landDetails'
        }

        self._created_by_user_id = created_by_user_id
        self._created_at = created_at
        self._updated_at = updated_at
        self._location = location
        self._communication = communication
        self._specification = specification
        self._external_id = external_id
        self._rent_offer = rent_offer
        self._sale_offer = sale_offer
        self._state = state
        self._client_lead_id = client_lead_id
        self._linked_contact_ids = linked_contact_ids
        self._additional_details = additional_details
        self._state_details = state_details
        self._responsible_user = responsible_user
        self._removal_order_id = removal_order_id
        self._updated_by_user_id = updated_by_user_id
        self._badge = badge
        self._category = category
        self._equipment = equipment
        self._kind = kind
        self._images = images
        self._layout_images = layout_images
        self._land_details = land_details

    @classmethod
    def from_dict(cls, dikt) -> 'PostPutCountryProperty':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostPutCountryProperty of this PostPutCountryProperty.  # noqa: E501
        :rtype: PostPutCountryProperty
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_by_user_id(self):
        """Gets the created_by_user_id of this PostPutCountryProperty.


        :return: The created_by_user_id of this PostPutCountryProperty.
        :rtype: int
        """
        return self._created_by_user_id

    @created_by_user_id.setter
    def created_by_user_id(self, created_by_user_id):
        """Sets the created_by_user_id of this PostPutCountryProperty.


        :param created_by_user_id: The created_by_user_id of this PostPutCountryProperty.
        :type created_by_user_id: int
        """

        self._created_by_user_id = created_by_user_id

    @property
    def created_at(self):
        """Gets the created_at of this PostPutCountryProperty.

        The date of creation  # noqa: E501

        :return: The created_at of this PostPutCountryProperty.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this PostPutCountryProperty.

        The date of creation  # noqa: E501

        :param created_at: The created_at of this PostPutCountryProperty.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this PostPutCountryProperty.


        :return: The updated_at of this PostPutCountryProperty.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this PostPutCountryProperty.


        :param updated_at: The updated_at of this PostPutCountryProperty.
        :type updated_at: str
        """

        self._updated_at = updated_at

    @property
    def location(self):
        """Gets the location of this PostPutCountryProperty.


        :return: The location of this PostPutCountryProperty.
        :rtype: PostPutCountryPropertyLocation
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this PostPutCountryProperty.


        :param location: The location of this PostPutCountryProperty.
        :type location: PostPutCountryPropertyLocation
        """

        self._location = location

    @property
    def communication(self):
        """Gets the communication of this PostPutCountryProperty.


        :return: The communication of this PostPutCountryProperty.
        :rtype: Communication
        """
        return self._communication

    @communication.setter
    def communication(self, communication):
        """Sets the communication of this PostPutCountryProperty.


        :param communication: The communication of this PostPutCountryProperty.
        :type communication: Communication
        """

        self._communication = communication

    @property
    def specification(self):
        """Gets the specification of this PostPutCountryProperty.


        :return: The specification of this PostPutCountryProperty.
        :rtype: Specification
        """
        return self._specification

    @specification.setter
    def specification(self, specification):
        """Sets the specification of this PostPutCountryProperty.


        :param specification: The specification of this PostPutCountryProperty.
        :type specification: Specification
        """

        self._specification = specification

    @property
    def external_id(self):
        """Gets the external_id of this PostPutCountryProperty.


        :return: The external_id of this PostPutCountryProperty.
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this PostPutCountryProperty.


        :param external_id: The external_id of this PostPutCountryProperty.
        :type external_id: str
        """

        self._external_id = external_id

    @property
    def rent_offer(self):
        """Gets the rent_offer of this PostPutCountryProperty.


        :return: The rent_offer of this PostPutCountryProperty.
        :rtype: RentOffer
        """
        return self._rent_offer

    @rent_offer.setter
    def rent_offer(self, rent_offer):
        """Sets the rent_offer of this PostPutCountryProperty.


        :param rent_offer: The rent_offer of this PostPutCountryProperty.
        :type rent_offer: RentOffer
        """

        self._rent_offer = rent_offer

    @property
    def sale_offer(self):
        """Gets the sale_offer of this PostPutCountryProperty.


        :return: The sale_offer of this PostPutCountryProperty.
        :rtype: SaleOffer
        """
        return self._sale_offer

    @sale_offer.setter
    def sale_offer(self, sale_offer):
        """Sets the sale_offer of this PostPutCountryProperty.


        :param sale_offer: The sale_offer of this PostPutCountryProperty.
        :type sale_offer: SaleOffer
        """

        self._sale_offer = sale_offer

    @property
    def state(self):
        """Gets the state of this PostPutCountryProperty.


        :return: The state of this PostPutCountryProperty.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this PostPutCountryProperty.


        :param state: The state of this PostPutCountryProperty.
        :type state: str
        """
        allowed_values = ["draft", "public", "postponed", "sold", "rented", "private", "deleted"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                    .format(state, allowed_values)
            )

        self._state = state

    @property
    def client_lead_id(self):
        """Gets the client_lead_id of this PostPutCountryProperty.


        :return: The client_lead_id of this PostPutCountryProperty.
        :rtype: int
        """
        return self._client_lead_id

    @client_lead_id.setter
    def client_lead_id(self, client_lead_id):
        """Sets the client_lead_id of this PostPutCountryProperty.


        :param client_lead_id: The client_lead_id of this PostPutCountryProperty.
        :type client_lead_id: int
        """

        self._client_lead_id = client_lead_id

    @property
    def linked_contact_ids(self):
        """Gets the linked_contact_ids of this PostPutCountryProperty.


        :return: The linked_contact_ids of this PostPutCountryProperty.
        :rtype: List[int]
        """
        return self._linked_contact_ids

    @linked_contact_ids.setter
    def linked_contact_ids(self, linked_contact_ids):
        """Sets the linked_contact_ids of this PostPutCountryProperty.


        :param linked_contact_ids: The linked_contact_ids of this PostPutCountryProperty.
        :type linked_contact_ids: List[int]
        """

        self._linked_contact_ids = linked_contact_ids

    @property
    def additional_details(self):
        """Gets the additional_details of this PostPutCountryProperty.


        :return: The additional_details of this PostPutCountryProperty.
        :rtype: GetCountryPropertyAdditionalDetails
        """
        return self._additional_details

    @additional_details.setter
    def additional_details(self, additional_details):
        """Sets the additional_details of this PostPutCountryProperty.


        :param additional_details: The additional_details of this PostPutCountryProperty.
        :type additional_details: GetCountryPropertyAdditionalDetails
        """

        self._additional_details = additional_details

    @property
    def state_details(self):
        """Gets the state_details of this PostPutCountryProperty.


        :return: The state_details of this PostPutCountryProperty.
        :rtype: GetCountryPropertyStateDetails
        """
        return self._state_details

    @state_details.setter
    def state_details(self, state_details):
        """Sets the state_details of this PostPutCountryProperty.


        :param state_details: The state_details of this PostPutCountryProperty.
        :type state_details: GetCountryPropertyStateDetails
        """

        self._state_details = state_details

    @property
    def responsible_user(self):
        """Gets the responsible_user of this PostPutCountryProperty.


        :return: The responsible_user of this PostPutCountryProperty.
        :rtype: StaffUser
        """
        return self._responsible_user

    @responsible_user.setter
    def responsible_user(self, responsible_user):
        """Sets the responsible_user of this PostPutCountryProperty.


        :param responsible_user: The responsible_user of this PostPutCountryProperty.
        :type responsible_user: StaffUser
        """

        self._responsible_user = responsible_user

    @property
    def removal_order_id(self):
        """Gets the removal_order_id of this PostPutCountryProperty.


        :return: The removal_order_id of this PostPutCountryProperty.
        :rtype: int
        """
        return self._removal_order_id

    @removal_order_id.setter
    def removal_order_id(self, removal_order_id):
        """Sets the removal_order_id of this PostPutCountryProperty.


        :param removal_order_id: The removal_order_id of this PostPutCountryProperty.
        :type removal_order_id: int
        """

        self._removal_order_id = removal_order_id

    @property
    def updated_by_user_id(self):
        """Gets the updated_by_user_id of this PostPutCountryProperty.


        :return: The updated_by_user_id of this PostPutCountryProperty.
        :rtype: int
        """
        return self._updated_by_user_id

    @updated_by_user_id.setter
    def updated_by_user_id(self, updated_by_user_id):
        """Sets the updated_by_user_id of this PostPutCountryProperty.


        :param updated_by_user_id: The updated_by_user_id of this PostPutCountryProperty.
        :type updated_by_user_id: int
        """

        self._updated_by_user_id = updated_by_user_id

    @property
    def badge(self):
        """Gets the badge of this PostPutCountryProperty.


        :return: The badge of this PostPutCountryProperty.
        :rtype: int
        """
        return self._badge

    @badge.setter
    def badge(self, badge):
        """Sets the badge of this PostPutCountryProperty.


        :param badge: The badge of this PostPutCountryProperty.
        :type badge: int
        """

        self._badge = badge

    @property
    def category(self):
        """Gets the category of this PostPutCountryProperty.


        :return: The category of this PostPutCountryProperty.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this PostPutCountryProperty.


        :param category: The category of this PostPutCountryProperty.
        :type category: str
        """

        self._category = category

    @property
    def equipment(self):
        """Gets the equipment of this PostPutCountryProperty.


        :return: The equipment of this PostPutCountryProperty.
        :rtype: List[str]
        """
        return self._equipment

    @equipment.setter
    def equipment(self, equipment):
        """Sets the equipment of this PostPutCountryProperty.


        :param equipment: The equipment of this PostPutCountryProperty.
        :type equipment: List[str]
        """

        self._equipment = equipment

    @property
    def kind(self):
        """Gets the kind of this PostPutCountryProperty.


        :return: The kind of this PostPutCountryProperty.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this PostPutCountryProperty.


        :param kind: The kind of this PostPutCountryProperty.
        :type kind: str
        """

        self._kind = kind

    @property
    def images(self):
        """Gets the images of this PostPutCountryProperty.


        :return: The images of this PostPutCountryProperty.
        :rtype: List[Image]
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this PostPutCountryProperty.


        :param images: The images of this PostPutCountryProperty.
        :type images: List[Image]
        """

        self._images = images

    @property
    def layout_images(self):
        """Gets the layout_images of this PostPutCountryProperty.


        :return: The layout_images of this PostPutCountryProperty.
        :rtype: List[Image]
        """
        return self._layout_images

    @layout_images.setter
    def layout_images(self, layout_images):
        """Sets the layout_images of this PostPutCountryProperty.


        :param layout_images: The layout_images of this PostPutCountryProperty.
        :type layout_images: List[Image]
        """

        self._layout_images = layout_images

    @property
    def land_details(self):
        """Gets the land_details of this PostPutCountryProperty.


        :return: The land_details of this PostPutCountryProperty.
        :rtype: GetCountryPropertyLandDetails
        """
        return self._land_details

    @land_details.setter
    def land_details(self, land_details):
        """Sets the land_details of this PostPutCountryProperty.


        :param land_details: The land_details of this PostPutCountryProperty.
        :type land_details: GetCountryPropertyLandDetails
        """

        self._land_details = land_details
