# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class PostPutCountryPropertyLocation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, latitude=None, longitude=None, settlement_id=None, street=None, house=None):  # noqa: E501
        """PostPutCountryPropertyLocation - a model defined in OpenAPI

        :param latitude: The latitude of this PostPutCountryPropertyLocation.  # noqa: E501
        :type latitude: str
        :param longitude: The longitude of this PostPutCountryPropertyLocation.  # noqa: E501
        :type longitude: str
        :param settlement_id: The settlement_id of this PostPutCountryPropertyLocation.  # noqa: E501
        :type settlement_id: int
        :param street: The street of this PostPutCountryPropertyLocation.  # noqa: E501
        :type street: str
        :param house: The house of this PostPutCountryPropertyLocation.  # noqa: E501
        :type house: str
        """
        self.openapi_types = {
            'latitude': str,
            'longitude': str,
            'settlement_id': int,
            'street': str,
            'house': str
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude',
            'settlement_id': 'settlementId',
            'street': 'street',
            'house': 'house'
        }

        self._latitude = latitude
        self._longitude = longitude
        self._settlement_id = settlement_id
        self._street = street
        self._house = house

    @classmethod
    def from_dict(cls, dikt) -> 'PostPutCountryPropertyLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostPutCountryProperty_location of this PostPutCountryPropertyLocation.  # noqa: E501
        :rtype: PostPutCountryPropertyLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self):
        """Gets the latitude of this PostPutCountryPropertyLocation.

        Широта  # noqa: E501

        :return: The latitude of this PostPutCountryPropertyLocation.
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this PostPutCountryPropertyLocation.

        Широта  # noqa: E501

        :param latitude: The latitude of this PostPutCountryPropertyLocation.
        :type latitude: str
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this PostPutCountryPropertyLocation.

        Долгота  # noqa: E501

        :return: The longitude of this PostPutCountryPropertyLocation.
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this PostPutCountryPropertyLocation.

        Долгота  # noqa: E501

        :param longitude: The longitude of this PostPutCountryPropertyLocation.
        :type longitude: str
        """

        self._longitude = longitude

    @property
    def settlement_id(self):
        """Gets the settlement_id of this PostPutCountryPropertyLocation.


        :return: The settlement_id of this PostPutCountryPropertyLocation.
        :rtype: int
        """
        return self._settlement_id

    @settlement_id.setter
    def settlement_id(self, settlement_id):
        """Sets the settlement_id of this PostPutCountryPropertyLocation.


        :param settlement_id: The settlement_id of this PostPutCountryPropertyLocation.
        :type settlement_id: int
        """
        if settlement_id is not None and settlement_id < 1:  # noqa: E501
            raise ValueError(
                "Invalid value for `settlement_id`, must be a value greater than or equal to `1`")  # noqa: E501

        self._settlement_id = settlement_id

    @property
    def street(self):
        """Gets the street of this PostPutCountryPropertyLocation.


        :return: The street of this PostPutCountryPropertyLocation.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this PostPutCountryPropertyLocation.


        :param street: The street of this PostPutCountryPropertyLocation.
        :type street: str
        """

        self._street = street

    @property
    def house(self):
        """Gets the house of this PostPutCountryPropertyLocation.


        :return: The house of this PostPutCountryPropertyLocation.
        :rtype: str
        """
        return self._house

    @house.setter
    def house(self, house):
        """Sets the house of this PostPutCountryPropertyLocation.


        :param house: The house of this PostPutCountryPropertyLocation.
        :type house: str
        """

        self._house = house
