# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class PropertyAdditionalDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, garage_area=None, parking_area=None, bathhouse_area=None, staff_house_area=None, spa_area=None,
                 security_house_area=None, guest_house_area=None):  # noqa: E501
        """PropertyAdditionalDetails - a model defined in OpenAPI

        :param garage_area: The garage_area of this PropertyAdditionalDetails.  # noqa: E501
        :type garage_area: float
        :param parking_area: The parking_area of this PropertyAdditionalDetails.  # noqa: E501
        :type parking_area: float
        :param bathhouse_area: The bathhouse_area of this PropertyAdditionalDetails.  # noqa: E501
        :type bathhouse_area: float
        :param staff_house_area: The staff_house_area of this PropertyAdditionalDetails.  # noqa: E501
        :type staff_house_area: float
        :param spa_area: The spa_area of this PropertyAdditionalDetails.  # noqa: E501
        :type spa_area: float
        :param security_house_area: The security_house_area of this PropertyAdditionalDetails.  # noqa: E501
        :type security_house_area: float
        :param guest_house_area: The guest_house_area of this PropertyAdditionalDetails.  # noqa: E501
        :type guest_house_area: float
        """
        self.openapi_types = {
            'garage_area': float,
            'parking_area': float,
            'bathhouse_area': float,
            'staff_house_area': float,
            'spa_area': float,
            'security_house_area': float,
            'guest_house_area': float
        }

        self.attribute_map = {
            'garage_area': 'garageArea',
            'parking_area': 'parkingArea',
            'bathhouse_area': 'bathhouseArea',
            'staff_house_area': 'staffHouseArea',
            'spa_area': 'spaArea',
            'security_house_area': 'securityHouseArea',
            'guest_house_area': 'guestHouseArea'
        }

        self._garage_area = garage_area
        self._parking_area = parking_area
        self._bathhouse_area = bathhouse_area
        self._staff_house_area = staff_house_area
        self._spa_area = spa_area
        self._security_house_area = security_house_area
        self._guest_house_area = guest_house_area

    @classmethod
    def from_dict(cls, dikt) -> 'PropertyAdditionalDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Property_additionalDetails of this PropertyAdditionalDetails.  # noqa: E501
        :rtype: PropertyAdditionalDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def garage_area(self):
        """Gets the garage_area of this PropertyAdditionalDetails.


        :return: The garage_area of this PropertyAdditionalDetails.
        :rtype: float
        """
        return self._garage_area

    @garage_area.setter
    def garage_area(self, garage_area):
        """Sets the garage_area of this PropertyAdditionalDetails.


        :param garage_area: The garage_area of this PropertyAdditionalDetails.
        :type garage_area: float
        """

        self._garage_area = garage_area

    @property
    def parking_area(self):
        """Gets the parking_area of this PropertyAdditionalDetails.


        :return: The parking_area of this PropertyAdditionalDetails.
        :rtype: float
        """
        return self._parking_area

    @parking_area.setter
    def parking_area(self, parking_area):
        """Sets the parking_area of this PropertyAdditionalDetails.


        :param parking_area: The parking_area of this PropertyAdditionalDetails.
        :type parking_area: float
        """

        self._parking_area = parking_area

    @property
    def bathhouse_area(self):
        """Gets the bathhouse_area of this PropertyAdditionalDetails.


        :return: The bathhouse_area of this PropertyAdditionalDetails.
        :rtype: float
        """
        return self._bathhouse_area

    @bathhouse_area.setter
    def bathhouse_area(self, bathhouse_area):
        """Sets the bathhouse_area of this PropertyAdditionalDetails.


        :param bathhouse_area: The bathhouse_area of this PropertyAdditionalDetails.
        :type bathhouse_area: float
        """

        self._bathhouse_area = bathhouse_area

    @property
    def staff_house_area(self):
        """Gets the staff_house_area of this PropertyAdditionalDetails.


        :return: The staff_house_area of this PropertyAdditionalDetails.
        :rtype: float
        """
        return self._staff_house_area

    @staff_house_area.setter
    def staff_house_area(self, staff_house_area):
        """Sets the staff_house_area of this PropertyAdditionalDetails.


        :param staff_house_area: The staff_house_area of this PropertyAdditionalDetails.
        :type staff_house_area: float
        """

        self._staff_house_area = staff_house_area

    @property
    def spa_area(self):
        """Gets the spa_area of this PropertyAdditionalDetails.


        :return: The spa_area of this PropertyAdditionalDetails.
        :rtype: float
        """
        return self._spa_area

    @spa_area.setter
    def spa_area(self, spa_area):
        """Sets the spa_area of this PropertyAdditionalDetails.


        :param spa_area: The spa_area of this PropertyAdditionalDetails.
        :type spa_area: float
        """

        self._spa_area = spa_area

    @property
    def security_house_area(self):
        """Gets the security_house_area of this PropertyAdditionalDetails.


        :return: The security_house_area of this PropertyAdditionalDetails.
        :rtype: float
        """
        return self._security_house_area

    @security_house_area.setter
    def security_house_area(self, security_house_area):
        """Sets the security_house_area of this PropertyAdditionalDetails.


        :param security_house_area: The security_house_area of this PropertyAdditionalDetails.
        :type security_house_area: float
        """

        self._security_house_area = security_house_area

    @property
    def guest_house_area(self):
        """Gets the guest_house_area of this PropertyAdditionalDetails.


        :return: The guest_house_area of this PropertyAdditionalDetails.
        :rtype: float
        """
        return self._guest_house_area

    @guest_house_area.setter
    def guest_house_area(self, guest_house_area):
        """Sets the guest_house_area of this PropertyAdditionalDetails.


        :param guest_house_area: The guest_house_area of this PropertyAdditionalDetails.
        :type guest_house_area: float
        """

        self._guest_house_area = guest_house_area
