# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class PropertyLandDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, area=None, landscape_kind=None, landscaping=None):  # noqa: E501
        """PropertyLandDetails - a model defined in OpenAPI

        :param area: The area of this PropertyLandDetails.  # noqa: E501
        :type area: float
        :param landscape_kind: The landscape_kind of this PropertyLandDetails.  # noqa: E501
        :type landscape_kind: List[str]
        :param landscaping: The landscaping of this PropertyLandDetails.  # noqa: E501
        :type landscaping: bool
        """
        self.openapi_types = {
            'area': float,
            'landscape_kind': List[str],
            'landscaping': bool
        }

        self.attribute_map = {
            'area': 'area',
            'landscape_kind': 'landscapeKind',
            'landscaping': 'landscaping'
        }

        self._area = area
        self._landscape_kind = landscape_kind
        self._landscaping = landscaping

    @classmethod
    def from_dict(cls, dikt) -> 'PropertyLandDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Property_landDetails of this PropertyLandDetails.  # noqa: E501
        :rtype: PropertyLandDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def area(self):
        """Gets the area of this PropertyLandDetails.


        :return: The area of this PropertyLandDetails.
        :rtype: float
        """
        return self._area

    @area.setter
    def area(self, area):
        """Sets the area of this PropertyLandDetails.


        :param area: The area of this PropertyLandDetails.
        :type area: float
        """

        self._area = area

    @property
    def landscape_kind(self):
        """Gets the landscape_kind of this PropertyLandDetails.


        :return: The landscape_kind of this PropertyLandDetails.
        :rtype: List[str]
        """
        return self._landscape_kind

    @landscape_kind.setter
    def landscape_kind(self, landscape_kind):
        """Sets the landscape_kind of this PropertyLandDetails.


        :param landscape_kind: The landscape_kind of this PropertyLandDetails.
        :type landscape_kind: List[str]
        """

        self._landscape_kind = landscape_kind

    @property
    def landscaping(self):
        """Gets the landscaping of this PropertyLandDetails.


        :return: The landscaping of this PropertyLandDetails.
        :rtype: bool
        """
        return self._landscaping

    @landscaping.setter
    def landscaping(self, landscaping):
        """Sets the landscaping of this PropertyLandDetails.


        :param landscaping: The landscaping of this PropertyLandDetails.
        :type landscaping: bool
        """

        self._landscaping = landscaping
