# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class RegionLocation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, country_id=None, country_name=None):  # noqa: E501
        """RegionLocation - a model defined in OpenAPI

        :param country_id: The country_id of this RegionLocation.  # noqa: E501
        :type country_id: int
        :param country_name: The country_name of this RegionLocation.  # noqa: E501
        :type country_name: str
        """
        self.openapi_types = {
            'country_id': int,
            'country_name': str
        }

        self.attribute_map = {
            'country_id': 'countryId',
            'country_name': 'countryName'
        }

        self._country_id = country_id
        self._country_name = country_name

    @classmethod
    def from_dict(cls, dikt) -> 'RegionLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Region_location of this RegionLocation.  # noqa: E501
        :rtype: RegionLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def country_id(self):
        """Gets the country_id of this RegionLocation.


        :return: The country_id of this RegionLocation.
        :rtype: int
        """
        return self._country_id

    @country_id.setter
    def country_id(self, country_id):
        """Sets the country_id of this RegionLocation.


        :param country_id: The country_id of this RegionLocation.
        :type country_id: int
        """

        self._country_id = country_id

    @property
    def country_name(self):
        """Gets the country_name of this RegionLocation.


        :return: The country_name of this RegionLocation.
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this RegionLocation.


        :param country_name: The country_name of this RegionLocation.
        :type country_name: str
        """

        self._country_name = country_name
