# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util

from .region_location import RegionLocation  # noqa: E501


class Region(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, kind_name=None, property_categories=None, aliases=None, location=None,
                 created_at=None, updated_at=None):  # noqa: E501
        """Region - a model defined in OpenAPI

        :param id: The id of this Region.  # noqa: E501
        :type id: int
        :param name: The name of this Region.  # noqa: E501
        :type name: str
        :param kind_name: The kind_name of this Region.  # noqa: E501
        :type kind_name: str
        :param property_categories: The property_categories of this Region.  # noqa: E501
        :type property_categories: List[str]
        :param aliases: The aliases of this Region.  # noqa: E501
        :type aliases: List[str]
        :param location: The location of this Region.  # noqa: E501
        :type location: RegionLocation
        :param created_at: The created_at of this Region.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Region.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'kind_name': str,
            'property_categories': List[str],
            'aliases': List[str],
            'location': RegionLocation,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'kind_name': 'kindName',
            'property_categories': 'propertyCategories',
            'aliases': 'aliases',
            'location': 'location',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._id = id
        self._name = name
        self._kind_name = kind_name
        self._property_categories = property_categories
        self._aliases = aliases
        self._location = location
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Region':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Region of this Region.  # noqa: E501
        :rtype: Region
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Region.


        :return: The id of this Region.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Region.


        :param id: The id of this Region.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Region.


        :return: The name of this Region.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Region.


        :param name: The name of this Region.
        :type name: str
        """

        self._name = name

    @property
    def kind_name(self):
        """Gets the kind_name of this Region.


        :return: The kind_name of this Region.
        :rtype: str
        """
        return self._kind_name

    @kind_name.setter
    def kind_name(self, kind_name):
        """Sets the kind_name of this Region.


        :param kind_name: The kind_name of this Region.
        :type kind_name: str
        """

        self._kind_name = kind_name

    @property
    def property_categories(self):
        """Gets the property_categories of this Region.


        :return: The property_categories of this Region.
        :rtype: List[str]
        """
        return self._property_categories

    @property_categories.setter
    def property_categories(self, property_categories):
        """Sets the property_categories of this Region.


        :param property_categories: The property_categories of this Region.
        :type property_categories: List[str]
        """

        self._property_categories = property_categories

    @property
    def aliases(self):
        """Gets the aliases of this Region.


        :return: The aliases of this Region.
        :rtype: List[str]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this Region.


        :param aliases: The aliases of this Region.
        :type aliases: List[str]
        """

        self._aliases = aliases

    @property
    def location(self):
        """Gets the location of this Region.


        :return: The location of this Region.
        :rtype: RegionLocation
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this Region.


        :param location: The location of this Region.
        :type location: RegionLocation
        """

        self._location = location

    @property
    def created_at(self):
        """Gets the created_at of this Region.

        The date of creation  # noqa: E501

        :return: The created_at of this Region.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Region.

        The date of creation  # noqa: E501

        :param created_at: The created_at of this Region.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this Region.

        The date of updation  # noqa: E501

        :return: The updated_at of this Region.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Region.

        The date of updation  # noqa: E501

        :param updated_at: The updated_at of this Region.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
