# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.multi_currency_price import MultiCurrencyPrice
from ..models.base_model_ import Model
from .. import util


class RentOffer(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, price=None, price_delta=None, agent_fixed_price=None, agent_fee=None, multi_currency_price=None,
                 currency=None, is_allowed_children=None, is_allowed_pets=None, is_disabled=None, deposit=None,
                 period=None):  # noqa: E501
        """RentOffer - a model defined in OpenAPI

        :param price: The price of this RentOffer.  # noqa: E501
        :type price: float
        :param price_delta: The price_delta of this RentOffer.  # noqa: E501
        :type price_delta: float
        :param agent_fixed_price: The agent_fixed_price of this RentOffer.  # noqa: E501
        :type agent_fixed_price: float
        :param agent_fee: The agent_fee of this RentOffer.  # noqa: E501
        :type agent_fee: float
        :param multi_currency_price: The multi_currency_price of this RentOffer.  # noqa: E501
        :type multi_currency_price: MultiCurrencyPrice
        :param currency: The currency of this RentOffer.  # noqa: E501
        :type currency: str
        :param is_allowed_children: The is_allowed_children of this RentOffer.  # noqa: E501
        :type is_allowed_children: bool
        :param is_allowed_pets: The is_allowed_pets of this RentOffer.  # noqa: E501
        :type is_allowed_pets: bool
        :param is_disabled: The is_disabled of this RentOffer.  # noqa: E501
        :type is_disabled: bool
        :param deposit: The deposit of this RentOffer.  # noqa: E501
        :type deposit: float
        :param period: The period of this RentOffer.  # noqa: E501
        :type period: str
        """
        self.openapi_types = {
            'price': float,
            'price_delta': float,
            'agent_fixed_price': float,
            'agent_fee': float,
            'multi_currency_price': MultiCurrencyPrice,
            'currency': str,
            'is_allowed_children': bool,
            'is_allowed_pets': bool,
            'is_disabled': bool,
            'deposit': float,
            'period': str
        }

        self.attribute_map = {
            'price': 'price',
            'price_delta': 'priceDelta',
            'agent_fixed_price': 'agentFixedPrice',
            'agent_fee': 'agentFee',
            'multi_currency_price': 'multiCurrencyPrice',
            'currency': 'currency',
            'is_allowed_children': 'isAllowedChildren',
            'is_allowed_pets': 'isAllowedPets',
            'is_disabled': 'isDisabled',
            'deposit': 'deposit',
            'period': 'period'
        }

        self._price = price
        self._price_delta = price_delta
        self._agent_fixed_price = agent_fixed_price
        self._agent_fee = agent_fee
        self._multi_currency_price = multi_currency_price
        self._currency = currency
        self._is_allowed_children = is_allowed_children
        self._is_allowed_pets = is_allowed_pets
        self._is_disabled = is_disabled
        self._deposit = deposit
        self._period = period

    @classmethod
    def from_dict(cls, dikt) -> 'RentOffer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RentOffer of this RentOffer.  # noqa: E501
        :rtype: RentOffer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def price(self):
        """Gets the price of this RentOffer.

        Цена продажи  # noqa: E501

        :return: The price of this RentOffer.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this RentOffer.

        Цена продажи  # noqa: E501

        :param price: The price of this RentOffer.
        :type price: float
        """

        self._price = price

    @property
    def price_delta(self):
        """Gets the price_delta of this RentOffer.


        :return: The price_delta of this RentOffer.
        :rtype: float
        """
        return self._price_delta

    @price_delta.setter
    def price_delta(self, price_delta):
        """Sets the price_delta of this RentOffer.


        :param price_delta: The price_delta of this RentOffer.
        :type price_delta: float
        """

        self._price_delta = price_delta

    @property
    def agent_fixed_price(self):
        """Gets the agent_fixed_price of this RentOffer.


        :return: The agent_fixed_price of this RentOffer.
        :rtype: float
        """
        return self._agent_fixed_price

    @agent_fixed_price.setter
    def agent_fixed_price(self, agent_fixed_price):
        """Sets the agent_fixed_price of this RentOffer.


        :param agent_fixed_price: The agent_fixed_price of this RentOffer.
        :type agent_fixed_price: float
        """

        self._agent_fixed_price = agent_fixed_price

    @property
    def agent_fee(self):
        """Gets the agent_fee of this RentOffer.


        :return: The agent_fee of this RentOffer.
        :rtype: float
        """
        return self._agent_fee

    @agent_fee.setter
    def agent_fee(self, agent_fee):
        """Sets the agent_fee of this RentOffer.


        :param agent_fee: The agent_fee of this RentOffer.
        :type agent_fee: float
        """

        self._agent_fee = agent_fee

    @property
    def multi_currency_price(self):
        """Gets the multi_currency_price of this RentOffer.


        :return: The multi_currency_price of this RentOffer.
        :rtype: MultiCurrencyPrice
        """
        return self._multi_currency_price

    @multi_currency_price.setter
    def multi_currency_price(self, multi_currency_price):
        """Sets the multi_currency_price of this RentOffer.


        :param multi_currency_price: The multi_currency_price of this RentOffer.
        :type multi_currency_price: MultiCurrencyPrice
        """

        self._multi_currency_price = multi_currency_price

    @property
    def currency(self):
        """Gets the currency of this RentOffer.

        Валюта продажи  # noqa: E501

        :return: The currency of this RentOffer.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this RentOffer.

        Валюта продажи  # noqa: E501

        :param currency: The currency of this RentOffer.
        :type currency: str
        """

        self._currency = currency

    @property
    def is_allowed_children(self):
        """Gets the is_allowed_children of this RentOffer.


        :return: The is_allowed_children of this RentOffer.
        :rtype: bool
        """
        return self._is_allowed_children

    @is_allowed_children.setter
    def is_allowed_children(self, is_allowed_children):
        """Sets the is_allowed_children of this RentOffer.


        :param is_allowed_children: The is_allowed_children of this RentOffer.
        :type is_allowed_children: bool
        """

        self._is_allowed_children = is_allowed_children

    @property
    def is_allowed_pets(self):
        """Gets the is_allowed_pets of this RentOffer.


        :return: The is_allowed_pets of this RentOffer.
        :rtype: bool
        """
        return self._is_allowed_pets

    @is_allowed_pets.setter
    def is_allowed_pets(self, is_allowed_pets):
        """Sets the is_allowed_pets of this RentOffer.


        :param is_allowed_pets: The is_allowed_pets of this RentOffer.
        :type is_allowed_pets: bool
        """

        self._is_allowed_pets = is_allowed_pets

    @property
    def is_disabled(self):
        """Gets the is_disabled of this RentOffer.


        :return: The is_disabled of this RentOffer.
        :rtype: bool
        """
        return self._is_disabled

    @is_disabled.setter
    def is_disabled(self, is_disabled):
        """Sets the is_disabled of this RentOffer.


        :param is_disabled: The is_disabled of this RentOffer.
        :type is_disabled: bool
        """

        self._is_disabled = is_disabled

    @property
    def deposit(self):
        """Gets the deposit of this RentOffer.


        :return: The deposit of this RentOffer.
        :rtype: float
        """
        return self._deposit

    @deposit.setter
    def deposit(self, deposit):
        """Sets the deposit of this RentOffer.


        :param deposit: The deposit of this RentOffer.
        :type deposit: float
        """

        self._deposit = deposit

    @property
    def period(self):
        """Gets the period of this RentOffer.


        :return: The period of this RentOffer.
        :rtype: str
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this RentOffer.


        :param period: The period of this RentOffer.
        :type period: str
        """
        allowed_values = [None, "day", "month", "year"]  # noqa: E501
        if period not in allowed_values:
            raise ValueError(
                "Invalid value for `period` ({0}), must be one of {1}"
                    .format(period, allowed_values)
            )

        self._period = period
