# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.multi_currency_price import MultiCurrencyPrice
from ..models.base_model_ import Model
from .. import util


class SaleOffer(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, price=None, price_delta=None, agent_fixed_price=None, agent_fee=None, kind=None,
                 multi_currency_price=None, is_bargain=None, is_resale=None, is_disabled=None, is_mortgage=None,
                 is_installment=None, currency=None):  # noqa: E501
        """SaleOffer - a model defined in OpenAPI

        :param price: The price of this SaleOffer.  # noqa: E501
        :type price: int
        :param price_delta: The price_delta of this SaleOffer.  # noqa: E501
        :type price_delta: float
        :param agent_fixed_price: The agent_fixed_price of this SaleOffer.  # noqa: E501
        :type agent_fixed_price: float
        :param agent_fee: The agent_fee of this SaleOffer.  # noqa: E501
        :type agent_fee: float
        :param kind: The kind of this SaleOffer.  # noqa: E501
        :type kind: str
        :param multi_currency_price: The multi_currency_price of this SaleOffer.  # noqa: E501
        :type multi_currency_price: MultiCurrencyPrice
        :param is_bargain: The is_bargain of this SaleOffer.  # noqa: E501
        :type is_bargain: bool
        :param is_resale: The is_resale of this SaleOffer.  # noqa: E501
        :type is_resale: bool
        :param is_disabled: The is_disabled of this SaleOffer.  # noqa: E501
        :type is_disabled: bool
        :param is_mortgage: The is_mortgage of this SaleOffer.  # noqa: E501
        :type is_mortgage: bool
        :param is_installment: The is_installment of this SaleOffer.  # noqa: E501
        :type is_installment: bool
        :param currency: The currency of this SaleOffer.  # noqa: E501
        :type currency: str
        """
        self.openapi_types = {
            'price': int,
            'price_delta': float,
            'agent_fixed_price': float,
            'agent_fee': float,
            'kind': str,
            'multi_currency_price': MultiCurrencyPrice,
            'is_bargain': bool,
            'is_resale': bool,
            'is_disabled': bool,
            'is_mortgage': bool,
            'is_installment': bool,
            'currency': str
        }

        self.attribute_map = {
            'price': 'price',
            'price_delta': 'priceDelta',
            'agent_fixed_price': 'agentFixedPrice',
            'agent_fee': 'agentFee',
            'kind': 'kind',
            'multi_currency_price': 'multiCurrencyPrice',
            'is_bargain': 'isBargain',
            'is_resale': 'isResale',
            'is_disabled': 'isDisabled',
            'is_mortgage': 'isMortgage',
            'is_installment': 'isInstallment',
            'currency': 'currency'
        }

        self._price = price
        self._price_delta = price_delta
        self._agent_fixed_price = agent_fixed_price
        self._agent_fee = agent_fee
        self._kind = kind
        self._multi_currency_price = multi_currency_price
        self._is_bargain = is_bargain
        self._is_resale = is_resale
        self._is_disabled = is_disabled
        self._is_mortgage = is_mortgage
        self._is_installment = is_installment
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'SaleOffer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SaleOffer of this SaleOffer.  # noqa: E501
        :rtype: SaleOffer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def price(self):
        """Gets the price of this SaleOffer.


        :return: The price of this SaleOffer.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this SaleOffer.


        :param price: The price of this SaleOffer.
        :type price: int
        """

        self._price = price

    @property
    def price_delta(self):
        """Gets the price_delta of this SaleOffer.


        :return: The price_delta of this SaleOffer.
        :rtype: float
        """
        return self._price_delta

    @price_delta.setter
    def price_delta(self, price_delta):
        """Sets the price_delta of this SaleOffer.


        :param price_delta: The price_delta of this SaleOffer.
        :type price_delta: float
        """

        self._price_delta = price_delta

    @property
    def agent_fixed_price(self):
        """Gets the agent_fixed_price of this SaleOffer.


        :return: The agent_fixed_price of this SaleOffer.
        :rtype: float
        """
        return self._agent_fixed_price

    @agent_fixed_price.setter
    def agent_fixed_price(self, agent_fixed_price):
        """Sets the agent_fixed_price of this SaleOffer.


        :param agent_fixed_price: The agent_fixed_price of this SaleOffer.
        :type agent_fixed_price: float
        """

        self._agent_fixed_price = agent_fixed_price

    @property
    def agent_fee(self):
        """Gets the agent_fee of this SaleOffer.


        :return: The agent_fee of this SaleOffer.
        :rtype: float
        """
        return self._agent_fee

    @agent_fee.setter
    def agent_fee(self, agent_fee):
        """Sets the agent_fee of this SaleOffer.


        :param agent_fee: The agent_fee of this SaleOffer.
        :type agent_fee: float
        """

        self._agent_fee = agent_fee

    @property
    def kind(self):
        """Gets the kind of this SaleOffer.


        :return: The kind of this SaleOffer.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this SaleOffer.


        :param kind: The kind of this SaleOffer.
        :type kind: str
        """

        self._kind = kind

    @property
    def multi_currency_price(self):
        """Gets the multi_currency_price of this SaleOffer.


        :return: The multi_currency_price of this SaleOffer.
        :rtype: MultiCurrencyPrice
        """
        return self._multi_currency_price

    @multi_currency_price.setter
    def multi_currency_price(self, multi_currency_price):
        """Sets the multi_currency_price of this SaleOffer.


        :param multi_currency_price: The multi_currency_price of this SaleOffer.
        :type multi_currency_price: MultiCurrencyPrice
        """

        self._multi_currency_price = multi_currency_price

    @property
    def is_bargain(self):
        """Gets the is_bargain of this SaleOffer.


        :return: The is_bargain of this SaleOffer.
        :rtype: bool
        """
        return self._is_bargain

    @is_bargain.setter
    def is_bargain(self, is_bargain):
        """Sets the is_bargain of this SaleOffer.


        :param is_bargain: The is_bargain of this SaleOffer.
        :type is_bargain: bool
        """

        self._is_bargain = is_bargain

    @property
    def is_resale(self):
        """Gets the is_resale of this SaleOffer.


        :return: The is_resale of this SaleOffer.
        :rtype: bool
        """
        return self._is_resale

    @is_resale.setter
    def is_resale(self, is_resale):
        """Sets the is_resale of this SaleOffer.


        :param is_resale: The is_resale of this SaleOffer.
        :type is_resale: bool
        """

        self._is_resale = is_resale

    @property
    def is_disabled(self):
        """Gets the is_disabled of this SaleOffer.


        :return: The is_disabled of this SaleOffer.
        :rtype: bool
        """
        return self._is_disabled

    @is_disabled.setter
    def is_disabled(self, is_disabled):
        """Sets the is_disabled of this SaleOffer.


        :param is_disabled: The is_disabled of this SaleOffer.
        :type is_disabled: bool
        """

        self._is_disabled = is_disabled

    @property
    def is_mortgage(self):
        """Gets the is_mortgage of this SaleOffer.

        Ипотека  # noqa: E501

        :return: The is_mortgage of this SaleOffer.
        :rtype: bool
        """
        return self._is_mortgage

    @is_mortgage.setter
    def is_mortgage(self, is_mortgage):
        """Sets the is_mortgage of this SaleOffer.

        Ипотека  # noqa: E501

        :param is_mortgage: The is_mortgage of this SaleOffer.
        :type is_mortgage: bool
        """

        self._is_mortgage = is_mortgage

    @property
    def is_installment(self):
        """Gets the is_installment of this SaleOffer.


        :return: The is_installment of this SaleOffer.
        :rtype: bool
        """
        return self._is_installment

    @is_installment.setter
    def is_installment(self, is_installment):
        """Sets the is_installment of this SaleOffer.


        :param is_installment: The is_installment of this SaleOffer.
        :type is_installment: bool
        """

        self._is_installment = is_installment

    @property
    def currency(self):
        """Gets the currency of this SaleOffer.

        Валюта продажи  # noqa: E501

        :return: The currency of this SaleOffer.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this SaleOffer.

        Валюта продажи  # noqa: E501

        :param currency: The currency of this SaleOffer.
        :type currency: str
        """

        self._currency = currency
