# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .layout import Layout
from .specification_layouts import SpecificationLayouts
from .. import util


class Specification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, loggias=None, bedrooms=None, area=None, elevators=None, balconies=None, roof_material=None,
                 legacy_layouts=None, renovate=None, layouts=None, wcs=None, rooms=None, ceiling_height=None,
                 with_ventilation=None, wall_material=None, condition=None, floors=None, furniture=None,
                 built_year=None, spaces=None, with_conditioning=None):  # noqa: E501
        """Specification - a model defined in OpenAPI

        :param loggias: The loggias of this Specification.  # noqa: E501
        :type loggias: int
        :param bedrooms: The bedrooms of this Specification.  # noqa: E501
        :type bedrooms: int
        :param area: The area of this Specification.  # noqa: E501
        :type area: float
        :param elevators: The elevators of this Specification.  # noqa: E501
        :type elevators: int
        :param balconies: The balconies of this Specification.  # noqa: E501
        :type balconies: int
        :param roof_material: The roof_material of this Specification.  # noqa: E501
        :type roof_material: str
        :param legacy_layouts: The legacy_layouts of this Specification.  # noqa: E501
        :type legacy_layouts: List[Layout]
        :param renovate: The renovate of this Specification.  # noqa: E501
        :type renovate: str
        :param layouts: The layouts of this Specification.  # noqa: E501
        :type layouts: SpecificationLayouts
        :param wcs: The wcs of this Specification.  # noqa: E501
        :type wcs: int
        :param rooms: The rooms of this Specification.  # noqa: E501
        :type rooms: int
        :param ceiling_height: The ceiling_height of this Specification.  # noqa: E501
        :type ceiling_height: float
        :param with_ventilation: The with_ventilation of this Specification.  # noqa: E501
        :type with_ventilation: bool
        :param wall_material: The wall_material of this Specification.  # noqa: E501
        :type wall_material: str
        :param condition: The condition of this Specification.  # noqa: E501
        :type condition: str
        :param floors: The floors of this Specification.  # noqa: E501
        :type floors: int
        :param furniture: The furniture of this Specification.  # noqa: E501
        :type furniture: str
        :param built_year: The built_year of this Specification.  # noqa: E501
        :type built_year: int
        :param spaces: The spaces of this Specification.  # noqa: E501
        :type spaces: List[int]
        :param with_conditioning: The with_conditioning of this Specification.  # noqa: E501
        :type with_conditioning: bool
        """
        self.openapi_types = {
            'loggias': int,
            'bedrooms': int,
            'area': float,
            'elevators': int,
            'balconies': int,
            'roof_material': str,
            'legacy_layouts': List[Layout],
            'renovate': str,
            'layouts': SpecificationLayouts,
            'wcs': int,
            'rooms': int,
            'ceiling_height': float,
            'with_ventilation': bool,
            'wall_material': str,
            'condition': str,
            'floors': int,
            'furniture': str,
            'built_year': int,
            'spaces': List[int],
            'with_conditioning': bool
        }

        self.attribute_map = {
            'loggias': 'loggias',
            'bedrooms': 'bedrooms',
            'area': 'area',
            'elevators': 'elevators',
            'balconies': 'balconies',
            'roof_material': 'roofMaterial',
            'legacy_layouts': 'legacyLayouts',
            'renovate': 'renovate',
            'layouts': 'layouts',
            'wcs': 'wcs',
            'rooms': 'rooms',
            'ceiling_height': 'ceilingHeight',
            'with_ventilation': 'withVentilation',
            'wall_material': 'wallMaterial',
            'condition': 'condition',
            'floors': 'floors',
            'furniture': 'furniture',
            'built_year': 'builtYear',
            'spaces': 'spaces',
            'with_conditioning': 'withConditioning'
        }

        self._loggias = loggias
        self._bedrooms = bedrooms
        self._area = area
        self._elevators = elevators
        self._balconies = balconies
        self._roof_material = roof_material
        self._legacy_layouts = legacy_layouts
        self._renovate = renovate
        self._layouts = layouts
        self._wcs = wcs
        self._rooms = rooms
        self._ceiling_height = ceiling_height
        self._with_ventilation = with_ventilation
        self._wall_material = wall_material
        self._condition = condition
        self._floors = floors
        self._furniture = furniture
        self._built_year = built_year
        self._spaces = spaces
        self._with_conditioning = with_conditioning

    @classmethod
    def from_dict(cls, dikt) -> 'Specification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Specification of this Specification.  # noqa: E501
        :rtype: Specification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def loggias(self):
        """Gets the loggias of this Specification.


        :return: The loggias of this Specification.
        :rtype: int
        """
        return self._loggias

    @loggias.setter
    def loggias(self, loggias):
        """Sets the loggias of this Specification.


        :param loggias: The loggias of this Specification.
        :type loggias: int
        """

        self._loggias = loggias

    @property
    def bedrooms(self):
        """Gets the bedrooms of this Specification.


        :return: The bedrooms of this Specification.
        :rtype: int
        """
        return self._bedrooms

    @bedrooms.setter
    def bedrooms(self, bedrooms):
        """Sets the bedrooms of this Specification.


        :param bedrooms: The bedrooms of this Specification.
        :type bedrooms: int
        """

        self._bedrooms = bedrooms

    @property
    def area(self):
        """Gets the area of this Specification.


        :return: The area of this Specification.
        :rtype: float
        """
        return self._area

    @area.setter
    def area(self, area):
        """Sets the area of this Specification.


        :param area: The area of this Specification.
        :type area: float
        """

        self._area = area

    @property
    def elevators(self):
        """Gets the elevators of this Specification.

        Колличество ливтов  # noqa: E501

        :return: The elevators of this Specification.
        :rtype: int
        """
        return self._elevators

    @elevators.setter
    def elevators(self, elevators):
        """Sets the elevators of this Specification.

        Колличество ливтов  # noqa: E501

        :param elevators: The elevators of this Specification.
        :type elevators: int
        """

        self._elevators = elevators

    @property
    def balconies(self):
        """Gets the balconies of this Specification.

        Количество балконов  # noqa: E501

        :return: The balconies of this Specification.
        :rtype: int
        """
        return self._balconies

    @balconies.setter
    def balconies(self, balconies):
        """Sets the balconies of this Specification.

        Количество балконов  # noqa: E501

        :param balconies: The balconies of this Specification.
        :type balconies: int
        """

        self._balconies = balconies

    @property
    def roof_material(self):
        """Gets the roof_material of this Specification.


        :return: The roof_material of this Specification.
        :rtype: str
        """
        return self._roof_material

    @roof_material.setter
    def roof_material(self, roof_material):
        """Sets the roof_material of this Specification.


        :param roof_material: The roof_material of this Specification.
        :type roof_material: str
        """
        allowed_values = ["steel", "soft_tile", "copper", "metal_tile", "slate", "tile", "rooftop"]  # noqa: E501
        if roof_material not in allowed_values:
            raise ValueError(
                "Invalid value for `roof_material` ({0}), must be one of {1}"
                    .format(roof_material, allowed_values)
            )

        self._roof_material = roof_material

    @property
    def legacy_layouts(self):
        """Gets the legacy_layouts of this Specification.


        :return: The legacy_layouts of this Specification.
        :rtype: List[Layout]
        """
        return self._legacy_layouts

    @legacy_layouts.setter
    def legacy_layouts(self, legacy_layouts):
        """Sets the legacy_layouts of this Specification.


        :param legacy_layouts: The legacy_layouts of this Specification.
        :type legacy_layouts: List[Layout]
        """

        self._legacy_layouts = legacy_layouts

    @property
    def renovate(self):
        """Gets the renovate of this Specification.


        :return: The renovate of this Specification.
        :rtype: str
        """
        return self._renovate

    @renovate.setter
    def renovate(self, renovate):
        """Sets the renovate of this Specification.


        :param renovate: The renovate of this Specification.
        :type renovate: str
        """
        allowed_values = ["design", "rough_finish", "full_construction", "partly_turnkey", "for_finishing",
                          "raw"]  # noqa: E501
        if renovate not in allowed_values:
            raise ValueError(
                "Invalid value for `renovate` ({0}), must be one of {1}"
                    .format(renovate, allowed_values)
            )

        self._renovate = renovate

    @property
    def layouts(self):
        """Gets the layouts of this Specification.


        :return: The layouts of this Specification.
        :rtype: SpecificationLayouts
        """
        return self._layouts

    @layouts.setter
    def layouts(self, layouts):
        """Sets the layouts of this Specification.


        :param layouts: The layouts of this Specification.
        :type layouts: SpecificationLayouts
        """

        self._layouts = layouts

    @property
    def wcs(self):
        """Gets the wcs of this Specification.


        :return: The wcs of this Specification.
        :rtype: int
        """
        return self._wcs

    @wcs.setter
    def wcs(self, wcs):
        """Sets the wcs of this Specification.


        :param wcs: The wcs of this Specification.
        :type wcs: int
        """

        self._wcs = wcs

    @property
    def rooms(self):
        """Gets the rooms of this Specification.


        :return: The rooms of this Specification.
        :rtype: int
        """
        return self._rooms

    @rooms.setter
    def rooms(self, rooms):
        """Sets the rooms of this Specification.


        :param rooms: The rooms of this Specification.
        :type rooms: int
        """

        self._rooms = rooms

    @property
    def ceiling_height(self):
        """Gets the ceiling_height of this Specification.


        :return: The ceiling_height of this Specification.
        :rtype: float
        """
        return self._ceiling_height

    @ceiling_height.setter
    def ceiling_height(self, ceiling_height):
        """Sets the ceiling_height of this Specification.


        :param ceiling_height: The ceiling_height of this Specification.
        :type ceiling_height: float
        """

        self._ceiling_height = ceiling_height

    @property
    def with_ventilation(self):
        """Gets the with_ventilation of this Specification.


        :return: The with_ventilation of this Specification.
        :rtype: bool
        """
        return self._with_ventilation

    @with_ventilation.setter
    def with_ventilation(self, with_ventilation):
        """Sets the with_ventilation of this Specification.


        :param with_ventilation: The with_ventilation of this Specification.
        :type with_ventilation: bool
        """

        self._with_ventilation = with_ventilation

    @property
    def wall_material(self):
        """Gets the wall_material of this Specification.


        :return: The wall_material of this Specification.
        :rtype: str
        """
        return self._wall_material

    @wall_material.setter
    def wall_material(self, wall_material):
        """Sets the wall_material of this Specification.


        :param wall_material: The wall_material of this Specification.
        :type wall_material: str
        """
        allowed_values = ["blue_max", "wood", "brick", "block", "monolith", "canadian_sip"]  # noqa: E501
        if wall_material not in allowed_values:
            raise ValueError(
                "Invalid value for `wall_material` ({0}), must be one of {1}"
                    .format(wall_material, allowed_values)
            )

        self._wall_material = wall_material

    @property
    def condition(self):
        """Gets the condition of this Specification.


        :return: The condition of this Specification.
        :rtype: str
        """
        return self._condition

    @condition.setter
    def condition(self, condition):
        """Sets the condition of this Specification.


        :param condition: The condition of this Specification.
        :type condition: str
        """
        allowed_values = ["great", "good", "normal", "bad"]  # noqa: E501
        if condition not in allowed_values:
            raise ValueError(
                "Invalid value for `condition` ({0}), must be one of {1}"
                    .format(condition, allowed_values)
            )

        self._condition = condition

    @property
    def floors(self):
        """Gets the floors of this Specification.


        :return: The floors of this Specification.
        :rtype: int
        """
        return self._floors

    @floors.setter
    def floors(self, floors):
        """Sets the floors of this Specification.


        :param floors: The floors of this Specification.
        :type floors: int
        """

        self._floors = floors

    @property
    def furniture(self):
        """Gets the furniture of this Specification.


        :return: The furniture of this Specification.
        :rtype: str
        """
        return self._furniture

    @furniture.setter
    def furniture(self, furniture):
        """Sets the furniture of this Specification.


        :param furniture: The furniture of this Specification.
        :type furniture: str
        """
        allowed_values = ["full", "partial", "absent"]  # noqa: E501
        if furniture not in allowed_values:
            raise ValueError(
                "Invalid value for `furniture` ({0}), must be one of {1}"
                    .format(furniture, allowed_values)
            )

        self._furniture = furniture

    @property
    def built_year(self):
        """Gets the built_year of this Specification.


        :return: The built_year of this Specification.
        :rtype: int
        """
        return self._built_year

    @built_year.setter
    def built_year(self, built_year):
        """Sets the built_year of this Specification.


        :param built_year: The built_year of this Specification.
        :type built_year: int
        """

        self._built_year = built_year

    @property
    def spaces(self):
        """Gets the spaces of this Specification.


        :return: The spaces of this Specification.
        :rtype: List[int]
        """
        return self._spaces

    @spaces.setter
    def spaces(self, spaces):
        """Sets the spaces of this Specification.


        :param spaces: The spaces of this Specification.
        :type spaces: List[int]
        """

        self._spaces = spaces

    @property
    def with_conditioning(self):
        """Gets the with_conditioning of this Specification.


        :return: The with_conditioning of this Specification.
        :rtype: bool
        """
        return self._with_conditioning

    @with_conditioning.setter
    def with_conditioning(self, with_conditioning):
        """Sets the with_conditioning of this Specification.


        :param with_conditioning: The with_conditioning of this Specification.
        :type with_conditioning: bool
        """

        self._with_conditioning = with_conditioning
