# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class SpecificationLayouts(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, spa_zone=None, office=None, technical_room=None, staff_room=None, dining_room=None,
                 winter_garden=None, kitchen=None, dressing_room=None, storage=None, utility_room=None, loft=None,
                 movie_theater=None, living_room=None):  # noqa: E501
        """SpecificationLayouts - a model defined in OpenAPI

        :param spa_zone: The spa_zone of this SpecificationLayouts.  # noqa: E501
        :type spa_zone: str
        :param office: The office of this SpecificationLayouts.  # noqa: E501
        :type office: str
        :param technical_room: The technical_room of this SpecificationLayouts.  # noqa: E501
        :type technical_room: str
        :param staff_room: The staff_room of this SpecificationLayouts.  # noqa: E501
        :type staff_room: str
        :param dining_room: The dining_room of this SpecificationLayouts.  # noqa: E501
        :type dining_room: str
        :param winter_garden: The winter_garden of this SpecificationLayouts.  # noqa: E501
        :type winter_garden: str
        :param kitchen: The kitchen of this SpecificationLayouts.  # noqa: E501
        :type kitchen: str
        :param dressing_room: The dressing_room of this SpecificationLayouts.  # noqa: E501
        :type dressing_room: str
        :param storage: The storage of this SpecificationLayouts.  # noqa: E501
        :type storage: str
        :param utility_room: The utility_room of this SpecificationLayouts.  # noqa: E501
        :type utility_room: str
        :param loft: The loft of this SpecificationLayouts.  # noqa: E501
        :type loft: str
        :param movie_theater: The movie_theater of this SpecificationLayouts.  # noqa: E501
        :type movie_theater: str
        :param living_room: The living_room of this SpecificationLayouts.  # noqa: E501
        :type living_room: str
        """
        self.openapi_types = {
            'spa_zone': str,
            'office': str,
            'technical_room': str,
            'staff_room': str,
            'dining_room': str,
            'winter_garden': str,
            'kitchen': str,
            'dressing_room': str,
            'storage': str,
            'utility_room': str,
            'loft': str,
            'movie_theater': str,
            'living_room': str
        }

        self.attribute_map = {
            'spa_zone': 'spa_zone',
            'office': 'office',
            'technical_room': 'technical_room',
            'staff_room': 'staff_room',
            'dining_room': 'dining_room',
            'winter_garden': 'winter_garden',
            'kitchen': 'kitchen',
            'dressing_room': 'dressing_room',
            'storage': 'storage',
            'utility_room': 'utility_room',
            'loft': 'loft',
            'movie_theater': 'movie_theater',
            'living_room': 'living_room'
        }

        self._spa_zone = spa_zone
        self._office = office
        self._technical_room = technical_room
        self._staff_room = staff_room
        self._dining_room = dining_room
        self._winter_garden = winter_garden
        self._kitchen = kitchen
        self._dressing_room = dressing_room
        self._storage = storage
        self._utility_room = utility_room
        self._loft = loft
        self._movie_theater = movie_theater
        self._living_room = living_room

    @classmethod
    def from_dict(cls, dikt) -> 'SpecificationLayouts':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Specification_layouts of this SpecificationLayouts.  # noqa: E501
        :rtype: SpecificationLayouts
        """
        return util.deserialize_model(dikt, cls)

    @property
    def spa_zone(self):
        """Gets the spa_zone of this SpecificationLayouts.


        :return: The spa_zone of this SpecificationLayouts.
        :rtype: str
        """
        return self._spa_zone

    @spa_zone.setter
    def spa_zone(self, spa_zone):
        """Sets the spa_zone of this SpecificationLayouts.


        :param spa_zone: The spa_zone of this SpecificationLayouts.
        :type spa_zone: str
        """

        self._spa_zone = spa_zone

    @property
    def office(self):
        """Gets the office of this SpecificationLayouts.


        :return: The office of this SpecificationLayouts.
        :rtype: str
        """
        return self._office

    @office.setter
    def office(self, office):
        """Sets the office of this SpecificationLayouts.


        :param office: The office of this SpecificationLayouts.
        :type office: str
        """

        self._office = office

    @property
    def technical_room(self):
        """Gets the technical_room of this SpecificationLayouts.


        :return: The technical_room of this SpecificationLayouts.
        :rtype: str
        """
        return self._technical_room

    @technical_room.setter
    def technical_room(self, technical_room):
        """Sets the technical_room of this SpecificationLayouts.


        :param technical_room: The technical_room of this SpecificationLayouts.
        :type technical_room: str
        """

        self._technical_room = technical_room

    @property
    def staff_room(self):
        """Gets the staff_room of this SpecificationLayouts.


        :return: The staff_room of this SpecificationLayouts.
        :rtype: str
        """
        return self._staff_room

    @staff_room.setter
    def staff_room(self, staff_room):
        """Sets the staff_room of this SpecificationLayouts.


        :param staff_room: The staff_room of this SpecificationLayouts.
        :type staff_room: str
        """

        self._staff_room = staff_room

    @property
    def dining_room(self):
        """Gets the dining_room of this SpecificationLayouts.


        :return: The dining_room of this SpecificationLayouts.
        :rtype: str
        """
        return self._dining_room

    @dining_room.setter
    def dining_room(self, dining_room):
        """Sets the dining_room of this SpecificationLayouts.


        :param dining_room: The dining_room of this SpecificationLayouts.
        :type dining_room: str
        """

        self._dining_room = dining_room

    @property
    def winter_garden(self):
        """Gets the winter_garden of this SpecificationLayouts.


        :return: The winter_garden of this SpecificationLayouts.
        :rtype: str
        """
        return self._winter_garden

    @winter_garden.setter
    def winter_garden(self, winter_garden):
        """Sets the winter_garden of this SpecificationLayouts.


        :param winter_garden: The winter_garden of this SpecificationLayouts.
        :type winter_garden: str
        """

        self._winter_garden = winter_garden

    @property
    def kitchen(self):
        """Gets the kitchen of this SpecificationLayouts.


        :return: The kitchen of this SpecificationLayouts.
        :rtype: str
        """
        return self._kitchen

    @kitchen.setter
    def kitchen(self, kitchen):
        """Sets the kitchen of this SpecificationLayouts.


        :param kitchen: The kitchen of this SpecificationLayouts.
        :type kitchen: str
        """

        self._kitchen = kitchen

    @property
    def dressing_room(self):
        """Gets the dressing_room of this SpecificationLayouts.


        :return: The dressing_room of this SpecificationLayouts.
        :rtype: str
        """
        return self._dressing_room

    @dressing_room.setter
    def dressing_room(self, dressing_room):
        """Sets the dressing_room of this SpecificationLayouts.


        :param dressing_room: The dressing_room of this SpecificationLayouts.
        :type dressing_room: str
        """

        self._dressing_room = dressing_room

    @property
    def storage(self):
        """Gets the storage of this SpecificationLayouts.


        :return: The storage of this SpecificationLayouts.
        :rtype: str
        """
        return self._storage

    @storage.setter
    def storage(self, storage):
        """Sets the storage of this SpecificationLayouts.


        :param storage: The storage of this SpecificationLayouts.
        :type storage: str
        """

        self._storage = storage

    @property
    def utility_room(self):
        """Gets the utility_room of this SpecificationLayouts.


        :return: The utility_room of this SpecificationLayouts.
        :rtype: str
        """
        return self._utility_room

    @utility_room.setter
    def utility_room(self, utility_room):
        """Sets the utility_room of this SpecificationLayouts.


        :param utility_room: The utility_room of this SpecificationLayouts.
        :type utility_room: str
        """

        self._utility_room = utility_room

    @property
    def loft(self):
        """Gets the loft of this SpecificationLayouts.


        :return: The loft of this SpecificationLayouts.
        :rtype: str
        """
        return self._loft

    @loft.setter
    def loft(self, loft):
        """Sets the loft of this SpecificationLayouts.


        :param loft: The loft of this SpecificationLayouts.
        :type loft: str
        """

        self._loft = loft

    @property
    def movie_theater(self):
        """Gets the movie_theater of this SpecificationLayouts.


        :return: The movie_theater of this SpecificationLayouts.
        :rtype: str
        """
        return self._movie_theater

    @movie_theater.setter
    def movie_theater(self, movie_theater):
        """Sets the movie_theater of this SpecificationLayouts.


        :param movie_theater: The movie_theater of this SpecificationLayouts.
        :type movie_theater: str
        """

        self._movie_theater = movie_theater

    @property
    def living_room(self):
        """Gets the living_room of this SpecificationLayouts.


        :return: The living_room of this SpecificationLayouts.
        :rtype: str
        """
        return self._living_room

    @living_room.setter
    def living_room(self, living_room):
        """Sets the living_room of this SpecificationLayouts.


        :param living_room: The living_room of this SpecificationLayouts.
        :type living_room: str
        """

        self._living_room = living_room
