# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class SubLocalityLocation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, country_id=None, country_name=None, region_id=None, region_name=None, district_id=None,
                 district_name=None, locality_id=None, locality_name=None):  # noqa: E501
        """SubLocalityLocation - a model defined in OpenAPI

        :param country_id: The country_id of this SubLocalityLocation.  # noqa: E501
        :type country_id: int
        :param country_name: The country_name of this SubLocalityLocation.  # noqa: E501
        :type country_name: str
        :param region_id: The region_id of this SubLocalityLocation.  # noqa: E501
        :type region_id: int
        :param region_name: The region_name of this SubLocalityLocation.  # noqa: E501
        :type region_name: str
        :param district_id: The district_id of this SubLocalityLocation.  # noqa: E501
        :type district_id: int
        :param district_name: The district_name of this SubLocalityLocation.  # noqa: E501
        :type district_name: str
        :param locality_id: The locality_id of this SubLocalityLocation.  # noqa: E501
        :type locality_id: int
        :param locality_name: The locality_name of this SubLocalityLocation.  # noqa: E501
        :type locality_name: str
        """
        self.openapi_types = {
            'country_id': int,
            'country_name': str,
            'region_id': int,
            'region_name': str,
            'district_id': int,
            'district_name': str,
            'locality_id': int,
            'locality_name': str
        }

        self.attribute_map = {
            'country_id': 'countryId',
            'country_name': 'countryName',
            'region_id': 'regionId',
            'region_name': 'regionName',
            'district_id': 'districtId',
            'district_name': 'districtName',
            'locality_id': 'localityId',
            'locality_name': 'localityName'
        }

        self._country_id = country_id
        self._country_name = country_name
        self._region_id = region_id
        self._region_name = region_name
        self._district_id = district_id
        self._district_name = district_name
        self._locality_id = locality_id
        self._locality_name = locality_name

    @classmethod
    def from_dict(cls, dikt) -> 'SubLocalityLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubLocality_location of this SubLocalityLocation.  # noqa: E501
        :rtype: SubLocalityLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def country_id(self):
        """Gets the country_id of this SubLocalityLocation.


        :return: The country_id of this SubLocalityLocation.
        :rtype: int
        """
        return self._country_id

    @country_id.setter
    def country_id(self, country_id):
        """Sets the country_id of this SubLocalityLocation.


        :param country_id: The country_id of this SubLocalityLocation.
        :type country_id: int
        """

        self._country_id = country_id

    @property
    def country_name(self):
        """Gets the country_name of this SubLocalityLocation.


        :return: The country_name of this SubLocalityLocation.
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this SubLocalityLocation.


        :param country_name: The country_name of this SubLocalityLocation.
        :type country_name: str
        """

        self._country_name = country_name

    @property
    def region_id(self):
        """Gets the region_id of this SubLocalityLocation.


        :return: The region_id of this SubLocalityLocation.
        :rtype: int
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this SubLocalityLocation.


        :param region_id: The region_id of this SubLocalityLocation.
        :type region_id: int
        """

        self._region_id = region_id

    @property
    def region_name(self):
        """Gets the region_name of this SubLocalityLocation.


        :return: The region_name of this SubLocalityLocation.
        :rtype: str
        """
        return self._region_name

    @region_name.setter
    def region_name(self, region_name):
        """Sets the region_name of this SubLocalityLocation.


        :param region_name: The region_name of this SubLocalityLocation.
        :type region_name: str
        """

        self._region_name = region_name

    @property
    def district_id(self):
        """Gets the district_id of this SubLocalityLocation.


        :return: The district_id of this SubLocalityLocation.
        :rtype: int
        """
        return self._district_id

    @district_id.setter
    def district_id(self, district_id):
        """Sets the district_id of this SubLocalityLocation.


        :param district_id: The district_id of this SubLocalityLocation.
        :type district_id: int
        """

        self._district_id = district_id

    @property
    def district_name(self):
        """Gets the district_name of this SubLocalityLocation.


        :return: The district_name of this SubLocalityLocation.
        :rtype: str
        """
        return self._district_name

    @district_name.setter
    def district_name(self, district_name):
        """Sets the district_name of this SubLocalityLocation.


        :param district_name: The district_name of this SubLocalityLocation.
        :type district_name: str
        """

        self._district_name = district_name

    @property
    def locality_id(self):
        """Gets the locality_id of this SubLocalityLocation.


        :return: The locality_id of this SubLocalityLocation.
        :rtype: int
        """
        return self._locality_id

    @locality_id.setter
    def locality_id(self, locality_id):
        """Sets the locality_id of this SubLocalityLocation.


        :param locality_id: The locality_id of this SubLocalityLocation.
        :type locality_id: int
        """

        self._locality_id = locality_id

    @property
    def locality_name(self):
        """Gets the locality_name of this SubLocalityLocation.


        :return: The locality_name of this SubLocalityLocation.
        :rtype: str
        """
        return self._locality_name

    @locality_name.setter
    def locality_name(self, locality_name):
        """Sets the locality_name of this SubLocalityLocation.


        :param locality_name: The locality_name of this SubLocalityLocation.
        :type locality_name: str
        """

        self._locality_name = locality_name
